/**
 * Content and copy tables from the design prototype.
 *
 * GENERATED by apps/web/scripts/convert-prototype.py — do not hand-edit.
 *
 * Lifted verbatim, including the Burmese table — the prototype is already bilingual,
 * which is what the backend language-pack work is being built against. This is a
 * mirror of the design, not a source of product strings.
 */
export const LINES: readonly (readonly [string, string, string, string])[] = [
  ["Light is fast, but it is not instant.", "Light is fast", "0.0–4.2s", "linear-gradient(150deg,#1b2a63,#070b1e 72%),radial-gradient(circle at 68% 26%,rgba(255,196,120,.55),transparent 52%)"],
  ["The Sun you see is eight minutes old.", "Eight minutes old", "4.2–8.9s", "linear-gradient(150deg,#5c3410,#120a04 74%),radial-gradient(circle at 40% 40%,rgba(255,210,120,.7),transparent 48%)"],
  ["Look far enough and you are looking backwards.", "Looking backwards", "8.9–14.0s", "linear-gradient(160deg,#2a1f5e,#0a0718 72%),radial-gradient(circle at 30% 70%,rgba(140,200,255,.5),transparent 54%)"],
  ["Webb sees infrared — heat that survived the trip.", "Infrared", "14.0–19.4s", "linear-gradient(150deg,#7a2f3c,#170609 74%),radial-gradient(circle at 62% 34%,rgba(255,140,110,.55),transparent 50%)"],
  ["Its mirror is six and a half metres of gold.", "6.5m of gold", "19.4–24.1s", "linear-gradient(150deg,#6b4a0d,#150e02 72%),radial-gradient(circle at 50% 45%,rgba(255,206,90,.62),transparent 52%)"],
  ["It sits a million miles from Earth, in permanent night.", "Permanent night", "24.1–29.6s", "linear-gradient(150deg,#0f2547,#04060f 74%),radial-gradient(circle at 74% 66%,rgba(110,190,255,.45),transparent 52%)"]
];

export const MY: Record<string, string> = {
  navOnboard: "စတင်ခြင်း", navStart: "အစ", navRecipe: "အစီအစဉ်", navBoard: "ဇာတ်ညွှန်း",
  navDeliver: "ထုတ်ယူရန်", navIdentity: "စတိုင်", navCredits: "ခရက်ဒစ်", navProfile: "ကျွန်ုပ်",
  tabCreate: "ဖန်တီးရန်", tabProjects: "ပရောဂျက်", tabCredits: "ခရက်ဒစ်", tabYou: "ကျွန်ုပ်",
  sideNew: "ဗီဒီယိုအသစ်", sideBoard: "ဇာတ်ညွှန်း", sideDeliver: "ထုတ်ယူရန်",
  sideIdentity: "စတိုင်အစုံ", sideCredits: "ခရက်ဒစ်", sideVoice: "အသံ ပြင်ဆင်ရန်",
  tProjects: "ပရောဂျက်များ", tNew: "ဗီဒီယိုအသစ်", tPlan: "အစီအစဉ်", tBoard: "ဇာတ်ညွှန်း", tDeliver: "ထုတ်ယူရန်",
  tIdentity: "စတိုင်အစုံ", tCredits: "ခရက်ဒစ်", tAccount: "အကောင့်", tSetup: "ပြင်ဆင်ရန်",
  credits: "ခရက်ဒစ်", creditsLeft: "ခရက်ဒစ် ကျန်သည်", freePlan: "အခမဲ့",
  startTitle: "ဒီနေ့ ဘာတင်မလဲ။",
  startSub: "လင့်ခ်၊ ဗီဒီယို ဒါမှမဟုတ် အကြံတစ်ခုပဲ ဖြစ်ဖြစ် ရပါတယ်။",
  canvasPh: "လင့်ခ်တစ်ခု ကူးထည့်ပါ၊ ဒါမှမဟုတ် လိုချင်တာကို ရေးပါ…",
  attach: "ဖိုင်တွဲရန်", record: "အသံသွင်းရန်", cont: "ဆက်လုပ်ရန်",
  tryLabel: "စမ်းကြည့်ပါ —", chip1: "ဆောင်းပါး လင့်ခ်", chip2: "ရှည်တဲ့ ပေါ့တ်ကတ်စ်", chip3: "ကိုယ်ရေးထားတဲ့ စာသား",
  pickUp: "ဆက်လုပ်ရန်", orNew: "အသစ် စတင်ရန်",
  fromArticle: "သင့်ဆောင်းပါးမှ",
  planLine: "တစ်မိနစ်စာ ဗီဒီယိုတစ်ခု — သင့်အသံနဲ့ ရှင်းပြပါမယ်။",
  rc1: "TikTok နဲ့ Reels အတွက်", rc2: "သင့်အသံ", rc3: "စာတန်းထိုး ကြီးကြီး",
  adjust: "ပြင်ရန်", orElse: "ဒါမှမဟုတ် တခြားလုပ်ရန်",
  r1n: "ကျွန်တော် စကားပြောရုံပဲ", r1d: "သင့်မျက်နှာနဲ့ အသံ",
  r2n: "ရှည်တဲ့ဗီဒီယိုကို ဖြတ်ရန်", r2d: "အကောင်းဆုံးအပိုင်းတွေ ရှာပေးမယ်",
  r3n: "စာတန်းထိုးပဲ ထည့်ရန်", r3d: "ဗီဒီယိုကို မပြောင်းဘဲ ထားမယ်",
  ctaDraft: "မူကြမ်း ပြပါ", reassure: "အရင်ကြည့်ပါ။ တကယ်လုပ်ချင်တဲ့ အပိုင်းအတွက်သာ ပိုပေးရပါမယ်။",
  playAll: "အားလုံး ကြည့်ရန်",
  boardBanner: "ဒါက မူကြမ်းပါ။ တကယ်လုပ်သင့်တဲ့ အပိုင်းတွေ ရွေးပါ။",
  scenes: "ခန်း", real: "တကယ်", draft: "မူကြမ်း", working: "လုပ်နေသည်",
  makeReal: "တကယ်လုပ်ရန်", chosen: "ရွေးပြီး ✓", realDone: "တကယ် ✓",
  tryAgain: "ထပ်စမ်းရန်", changeWords: "စာသား ပြင်ရန်", moveUp: "အပေါ်တင်ရန်", moveDown: "အောက်ချရန်", remove: "ဖျက်ရန်",
  addScene: "ခန်းတစ်ခု ထည့်ရန်",
  chooseScenes: "တကယ်လုပ်သင့်တဲ့ ခန်းတွေ ရွေးပါ", chosenN: "ခန်း ရွေးပြီး",
  makeThemReal: "တကယ်လုပ်ရန်", saveDraft: "မူကြမ်း သိမ်းရန်", deliverBtn: "ထုတ်ယူရန်",
  busyReal: "ဒီခန်းကို တကယ်လုပ်နေသည်", busyRedo: "ဒီခန်းကိုပဲ ပြန်လုပ်နေသည်",
  deliverSub: "တင်မယ့် နေရာအတွက် လုပ်ပါ။",
  fTall: "မတ်", fSquare: "စတုရန်း", fWide: "ကျယ်",
  makeIt: "လုပ်ရန်", download: "ဒေါင်းလုဒ်", workingBtn: "လုပ်နေသည်…",
  closeNotice: "ပိတ်ထားလို့ ရပါတယ် — ပြီးရင် အကြောင်းကြားပါမယ်။",
  postTo: "တင်မယ့်နေရာ", yourCaption: "သင့်စာသား", edit: "ပြင်ရန်",
  makeAll: "သုံးမျိုးလုံး လုပ်ရန်", allReady: "သုံးမျိုးလုံး ပြီးပါပြီ",
  idTitle: "စတိုင်အစုံ", idSub: "တစ်ခါ သတ်မှတ်ပါ။ ဗီဒီယိုတိုင်း ကိုက်ညီပါမယ်။",
  yourVoice: "သင့်အသံ", usedIn: "ဗီဒီယိုတိုင်းမှာ သုံးပါမယ်", ready: "အဆင်သင့်",
  reRecord: "ပြန်သွင်းရန်", hearSample: "နမူနာ နားထောင်ရန", del: "ဖျက်ရန်",
  look: "အသွင်အပြင်", logo: "လိုဂို", palette: "အရောင်", type: "စာလုံး", introOutro: "အစ / အဆုံး",
  captionStyle: "စာတန်းထိုး ပုံစံ",
  seriesMem: "ဆက်တိုက် မှတ်ထားရန်", seriesSub: "နောက်ဗီဒီယိုကို ဒီပုံစံအတိုင်း ထားပါမယ်",
  balance: "လက်ကျန်", freeLine: "လစဉ် အခမဲ့။ ၂၀၀ ကို ၁၁ ရက်အတွင်း ထပ်ရပါမယ်။",
  costHeading: "ဈေးနှုန်း (ခရက်ဒစ်ဖြင့်)",
  p1: "ဗီဒီယိုတစ်ခုလုံး မူကြမ်း ကြည့်ရန်", p2: "ခန်းတစ်ခု တကယ်လုပ်ရန်",
  p3: "နေရာတစ်ခုအတွက် သိမ်းရန်", p4: "ခန်းတစ်ခု ထပ်စမ်းရန်", free: "အခမဲ့",
  recent: "မကြာသေးမီက", topUp: "ဖြည့်ရန်", bestValue: "အတန်ဆုံး", noSub: "စာရင်းသွင်းစရာ မလိုပါ။ ခရက်ဒစ် သက်တမ်း မကုန်ပါ။",
  l1: "ခန်း ၂ ခု တကယ်လုပ်ခဲ့", l2: "Webb ဗီဒီယို မူကြမ်း", l3: "TikTok အတွက် သိမ်းခဲ့", l4: "လစဉ် အခမဲ့ ခရက်ဒစ်",
  today: "ယနေ့", d3: "၃ ရက်က", d17: "၁၇ ရက်က",
  ep: "အပိုင်း", dAgo: "ရက်က", wAgo: "ပတ်က",
  published: "ဗီဒီယို ၄၇ ခု တင်ပြီး", thisMonth: "ဒီလ", nShorts: "ဗီဒီယို ၉ ခု", across: "ဇာတ်လမ်း ၂ ခုမှာ",
  voiceReady: "အသံ အဆင်သင့် · အရောင်၊ စာတန်း သတ်မှတ်ပြီး",
  account: "အကောင့်", plan: "အစီအစဉ်", connected: "ချိတ်ဆက်ထားသော", linked: "၃ ခု ချိတ်ပြီး",
  language: "ဘာသာစကား", myanmar: "မြန်မာ", notif: "အကြောင်းကြားချက်", whenDone: "ပြီးတဲ့အခါ",
  privacy: "ကိုယ်ရေးအချက်အလက်", signOut: "ထွက်ရန်",
  lastStep: "နောက်ဆုံးအဆင့် · တစ်မိနစ်", readAloud: "ဒါကို အသံထွက် ဖတ်ပါ",
  obSub: "ပြီးရင် ဗီဒီယိုတိုင်းကို သင့်အသံနဲ့ ပြောပေးနိုင်ပါပြီ။",
  obLine: "“ကျွန်တော် အာကာသအကြောင်း ဗီဒီယိုတိုတွေ လုပ်ပါတယ်။ ကိုယ့်အသံလိုပဲ ဖြစ်စေချင်ပါတယ်။”",
  recStart: "စတင်ရန် နှိပ်ပါ။", recGoing: "နားထောင်နေသည်… ပုံမှန်အတိုင်း ဆက်ဖတ်ပါ။",
  recPaused: "ခဏရပ်ထားသည်။ ဆက်ရန် နှိပ်ပါ။", recDone: "လုံလောက်ပါပြီ — အသံ အဆင်သင့်ဖြစ်ပါပြီ။",
  finish: "ပြီးပါပြီ", stockVoice: "အဆင်သင့်အသံ သုံးရန်", skip: "ကျော်ရန်",
  privacyNote: "ဒီအသံကို သင်သာ သုံးနိုင်ပါတယ်။ အချိန်မရွေး ဖျက်နိုင်ပါတယ်။",
  workspace: "အလုပ်နေရာ", freeResets: "အခမဲ့ ခရက်ဒစ် ၁၁ ရက်အတွင်း ပြန်ဖြည့်မည်",
  logoPlace: "ညာဘက်အောက်၊ ၂ စက္ကန့် ပျောက်", stingVal: "၂ စက္ကန့် လိုဂို · Subscribe ကတ်",
  capPop: "ထင်ရှားသော", capClean: "ရိုးရှင်းသော", capGlow: "အလင်းရောင်",
  projectsTitle: "သင့်ပရောဂျက်များ", newShort: "အသစ်", posted: "တင်ပြီး",
  videoLang: "ဗီဒီယို ဘာသာစကား",
  videoLangHelp: "သင့်ဗီဒီယိုတွေကို ပြောမယ့်၊ စာတန်းထိုးမယ့် ဘာသာစကား။"
};

export const SCREENS = ["onboard", "start", "recipe", "board", "deliver", "identity", "credits", "profile"];
export const TITLES: Record<string, string> = {
  onboard: "Set up", start: "New short", recipe: "The plan", board: "Storyboard",
  deliver: "Deliver", identity: "Identity kit", credits: "Credits", profile: "Account"
};
