/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * The design prototype's markup, as JSX.
 *
 * GENERATED by apps/web/scripts/convert-prototype.py — do not hand-edit.
 *
 * Every CSS string here is byte-identical to the design export. That is the point: it makes
 * "does this match the design" a property of the converter rather than of a thousand hand
 * transcriptions. Re-run the script instead of editing this file.
 *
 * Scoping note: `s` is both the shared style table and the scene loop variable, as in the
 * prototype. The emitted `.map((s: any) => ...)` parameter shadows the destructured binding
 * inside the storyboard, reproducing the prototype's own template scoping.
 */
import React from 'react'
import { createPortal } from 'react-dom'

import { hv, sx } from '../lib/sx'
import logoUrl from '../assets/lumina-disc.png'

/** Top bar, variant switcher, and the device shell with its (empty) content slots. */
function PrototypeChrome({ v }: { v: any }) {
  const {
    L,
    balance,
    balancePill,
    deskScreenStyle,
    deskWrapStyle,
    goBack,
    goCredits,
    goProfile,
    goStart,
    meterFillStyle,
    navItems,
    phoneHeaderStyle,
    phoneScreenStyle,
    phoneWrapStyle,
    screenTitle,
    shellStyle,
    showBack,
    showBalancePill,
    showLogo,
    showMeter,
    showTabs,
    sideNav,
    starsStyle,
    tabs,
    variantGroups,
  } = v
  return (
    <>
      <div style={sx("min-height:100vh;background:radial-gradient(1100px 700px at 15% -10%, rgba(70,110,220,.20), transparent 60%),radial-gradient(900px 600px at 88% 8%, rgba(255,170,70,.12), transparent 62%),radial-gradient(1000px 800px at 50% 110%, rgba(90,60,190,.18), transparent 60%),#05060f;padding:22px 24px 60px")}>
        <div style={sx("max-width:1420px;margin:0 auto;display:flex;flex-wrap:wrap;align-items:center;gap:16px 20px;padding-bottom:20px;border-bottom:1px solid rgba(150,170,230,.13)")} data-lum="harness">
          <div style={sx("display:flex;align-items:center;gap:11px")}>
            <img src={logoUrl} alt={"Lumina"} style={sx("width:38px;height:38px;display:block;filter:drop-shadow(0 0 14px rgba(120,170,255,.45))")} />
            <div style={sx("display:flex;flex-direction:column;gap:2px")}>
              <span style={sx("font:600 19px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;letter-spacing:-.01em")}>
                Lumina
              </span>
              <span style={sx("font:400 11px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad")}>
                Web app · all screens
              </span>
            </div>
          </div>
          <div style={sx("display:flex;flex-wrap:wrap;gap:4px;padding:4px;background:rgba(18,22,42,.85);border:1px solid rgba(150,170,230,.14);border-radius:11px")}>
            {(navItems ?? []).map((nv: any, i0: number) => (
              <React.Fragment key={i0}>
                {(nv.on) ? (
                  <>
                    <button onClick={nv.go} style={sx("padding:8px 12px;border:none;border-radius:8px;cursor:pointer;white-space:nowrap;font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;background:linear-gradient(135deg,#ffc36b,#ff8f3d);color:#1a1103")}>
                      <span className="sc-interp">{nv.label}</span>
                    </button>
                  </>
                ) : null}
                {(nv.off) ? (
                  <>
                    <button onClick={nv.go} style={sx("padding:8px 12px;border:none;border-radius:8px;cursor:pointer;white-space:nowrap;font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;background:transparent;color:#8b95b8")} className={hv("color:#dfe6ff")}>
                      <span className="sc-interp">{nv.label}</span>
                    </button>
                  </>
                ) : null}
              </React.Fragment>
            ))}
          </div>
          <div style={sx("flex:1")} />
          <div style={sx("display:flex;flex-wrap:wrap;gap:14px;align-items:flex-end")}>
            {(variantGroups ?? []).map((g: any, i0: number) => (
              <React.Fragment key={i0}>
                <div style={sx("display:flex;flex-direction:column;gap:5px")}>
                  <span style={sx("font:500 10px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0")}>
                    <span className="sc-interp">{g.label}</span>
                  </span>
                  <div style={sx("display:flex;gap:3px;padding:3px;background:rgba(18,22,42,.85);border:1px solid rgba(150,170,230,.14);border-radius:9px")}>
                    {(g.opts ?? []).map((o: any, i1: number) => (
                      <React.Fragment key={i1}>
                        {(o.on) ? (
                          <>
                            <button onClick={o.go} style={sx("padding:6px 10px;border:none;border-radius:7px;cursor:pointer;white-space:nowrap;font:500 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;background:rgba(150,180,255,.22);color:#e9efff")}>
                              <span className="sc-interp">{o.label}</span>
                            </button>
                          </>
                        ) : null}
                        {(o.off) ? (
                          <>
                            <button onClick={o.go} style={sx("padding:6px 10px;border:none;border-radius:7px;cursor:pointer;white-space:nowrap;font:500 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;background:transparent;color:#7d88ad")} className={hv("color:#c3cbe9")}>
                              <span className="sc-interp">{o.label}</span>
                            </button>
                          </>
                        ) : null}
                      </React.Fragment>
                    ))}
                  </div>
                </div>
              </React.Fragment>
            ))}
          </div>
        </div>
        <div style={sx("display:flex;justify-content:center;padding-top:34px")}>
          <div style={sx(shellStyle)}>
            <div style={sx(phoneWrapStyle)}>
              <div style={sx(phoneScreenStyle)}>
                <div style={sx(starsStyle)} />
                <div style={sx("display:flex;align-items:center;justify-content:space-between;padding:14px 26px 6px;font:600 13px/1.2 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#cfd6ef;flex:none;position:relative")}>
                  <span>
                    9:41
                  </span>
                  <div style={sx("width:78px;height:23px;background:#000;border-radius:20px;margin-top:-4px")} />
                  <span style={sx("display:flex;align-items:center;gap:6px")}>
                    <span style={sx("display:flex;align-items:flex-end;gap:1.5px;height:10px")}>
                      <span style={sx("width:3px;height:4px;background:#cfd6ef;border-radius:1px")} />
                      <span style={sx("width:3px;height:6px;background:#cfd6ef;border-radius:1px")} />
                      <span style={sx("width:3px;height:8px;background:#cfd6ef;border-radius:1px")} />
                      <span style={sx("width:3px;height:10px;background:#cfd6ef;border-radius:1px")} />
                    </span>
                    <span style={sx("display:flex;align-items:center;gap:1px")}>
                      <span style={sx("width:22px;height:11px;border:1.4px solid rgba(207,214,239,.6);border-radius:3px;padding:1.4px;display:block")}>
                        <span style={sx("display:block;width:100%;height:100%;background:#cfd6ef;border-radius:1px")} />
                      </span>
                      <span style={sx("width:2px;height:4px;background:rgba(207,214,239,.6);border-radius:0 1px 1px 0")} />
                    </span>
                  </span>
                </div>
                <div style={sx(phoneHeaderStyle)}>
                  {(showBack) ? (
                    <>
                      <button onClick={goBack} style={sx("width:32px;height:32px;flex:none;border-radius:9px;background:rgba(150,170,230,.09);border:1px solid rgba(150,170,230,.16);color:#cfd8f7;font-size:15px;cursor:pointer;padding:0")}>
                        ‹
                      </button>
                    </>
                  ) : null}
                  {(showLogo) ? (
                    <>
                      <img src={logoUrl} alt={""} style={sx("width:26px;height:26px;display:block;flex:none")} />
                    </>
                  ) : null}
                  <span style={sx("font:600 15px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap")}>
                    <span className="sc-interp">{screenTitle}</span>
                  </span>
                  {(showMeter) ? (
                    <>
                      <button onClick={goCredits} style={sx("display:flex;align-items:center;gap:7px;padding:5px 9px 5px 7px;background:rgba(20,25,48,.9);border:1px solid rgba(150,170,230,.16);border-radius:20px;cursor:pointer;flex:none")}>
                        <span style={sx("width:34px;height:5px;background:rgba(150,170,230,.2);border-radius:4px;overflow:hidden;display:block")}>
                          <span style={sx(meterFillStyle)} />
                        </span>
                        <span style={sx("font:600 11px/1.2 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#ffc36b")}>
                          <span className="sc-interp">{balance}</span>
                        </span>
                      </button>
                    </>
                  ) : null}
                  {(showBalancePill) ? (
                    <>
                      <button onClick={goCredits} style={sx("font:600 11.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#ffc36b;padding:7px 10px;background:rgba(255,170,70,.10);border:1px solid rgba(255,170,70,.24);border-radius:20px;cursor:pointer;flex:none")}>
                        <span className="sc-interp">{balancePill}</span>
                      </button>
                    </>
                  ) : null}
                  <button onClick={goProfile} style={sx("width:32px;height:32px;flex:none;border-radius:50%;border:1px solid rgba(150,180,255,.3);background:linear-gradient(140deg,#ff9f45,#b45cff);color:#fff;font:600 12px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;cursor:pointer;padding:0")} className={hv("filter:brightness(1.1)")}>
                    SR
                  </button>
                </div>
                <div style={sx("flex:1;min-height:0;overflow-y:auto;position:relative")}>
                  <div id={"lum-slot-phone"} style={sx("min-height:100%")} />
                </div>
                {(showTabs) ? (
                  <>
                    <div style={sx("flex:none;display:flex;padding:8px 10px 22px;gap:2px;background:linear-gradient(180deg,rgba(7,10,22,.5),rgba(7,10,22,.97));backdrop-filter:blur(14px);border-top:1px solid rgba(150,170,230,.13);position:relative")}>
                      {(tabs ?? []).map((t: any, i0: number) => (
                        <React.Fragment key={i0}>
                          {(t.on) ? (
                            <>
                              <button onClick={t.go} style={sx("flex:1;min-width:0;display:flex;flex-direction:column;align-items:center;gap:4px;padding:7px 4px;background:transparent;border:none;cursor:pointer;min-height:52px")}>
                                <span style={sx("display:flex;align-items:center;justify-content:center;width:30px;height:26px;border-radius:9px;background:rgba(255,195,107,.16)")}>
                                  <svg width={"19"} height={"19"} viewBox={"0 0 24 24"} fill={"none"} stroke={"#ffc36b"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"}>
                                    <path d={t.d} />
                                  </svg>
                                </span>
                                <span style={sx("font:600 10px/1.3 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#ffc36b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%")}>
                                  <span className="sc-interp">{t.label}</span>
                                </span>
                              </button>
                            </>
                          ) : null}
                          {(t.off) ? (
                            <>
                              <button onClick={t.go} style={sx("flex:1;min-width:0;display:flex;flex-direction:column;align-items:center;gap:4px;padding:7px 4px;background:transparent;border:none;cursor:pointer;min-height:52px")} className={hv("opacity:.8")}>
                                <span style={sx("display:flex;align-items:center;justify-content:center;width:30px;height:26px")}>
                                  <svg width={"19"} height={"19"} viewBox={"0 0 24 24"} fill={"none"} stroke={"#7d88ad"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"}>
                                    <path d={t.d} />
                                  </svg>
                                </span>
                                <span style={sx("font:500 10px/1.3 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%")}>
                                  <span className="sc-interp">{t.label}</span>
                                </span>
                              </button>
                            </>
                          ) : null}
                        </React.Fragment>
                      ))}
                    </div>
                  </>
                ) : null}
              </div>
            </div>
            <div style={sx(deskWrapStyle)}>
              <div style={sx("width:100%;height:100%;display:flex;flex-direction:column;background:#070a16;border-radius:14px;overflow:hidden;border:1px solid rgba(150,170,230,.14)")} data-lum="window">
                <div style={sx("display:flex;align-items:center;gap:9px;padding:11px 16px;background:rgba(12,16,32,.9);border-bottom:1px solid rgba(150,170,230,.12);flex:none")} data-lum="titlebar">
                  <span style={sx("width:11px;height:11px;border-radius:50%;background:#ff5f57")} />
                  <span style={sx("width:11px;height:11px;border-radius:50%;background:#febc2e")} />
                  <span style={sx("width:11px;height:11px;border-radius:50%;background:#28c840")} />
                  <span style={sx("flex:1;text-align:center;font:400 12px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0")}>
                    lumina.app/project/webb-explainer
                  </span>
                </div>
                <div style={sx("flex:1;min-height:0;display:flex")}>
                  <div style={sx("width:232px;flex:none;border-right:1px solid rgba(150,170,230,.12);background:rgba(10,13,28,.7);padding:18px 14px;display:flex;flex-direction:column;gap:20px;overflow-y:auto")} data-lum="sidebar">
                    <div style={sx("display:flex;align-items:center;gap:10px")}>
                      <img src={logoUrl} alt={""} style={sx("width:30px;height:30px;display:block")} />
                      <span style={sx("font:600 17px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif")}>
                        Lumina
                      </span>
                    </div>
                    <button onClick={goStart} style={sx("display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:11px 13px;background:linear-gradient(135deg,#ffb347,#ff8a3d);border:none;border-radius:11px;color:#1a1103;font:600 13.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;box-shadow:0 6px 20px rgba(255,150,60,.26)")} className={hv("filter:brightness(1.06)")}>
                      <span style={sx("font-size:15px;line-height:1")}>
                        ＋
                      </span>
                      <span className="sc-interp">{L.sideNew}</span> 
                    </button>
                    <div style={sx("display:flex;flex-direction:column;gap:2px")}>
                      <span style={sx("font:500 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0;padding:0 12px 8px")}>
                        <span className="sc-interp">{L.workspace}</span>
                      </span>
                      {(sideNav ?? []).map((sn: any, i0: number) => (
                        <React.Fragment key={i0}>
                          {(sn.on) ? (
                            <>
                              <button onClick={sn.go} style={sx("display:flex;align-items:center;gap:10px;width:100%;padding:9px 12px;border:none;border-radius:9px;cursor:pointer;font:500 13px/1.5 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;background:rgba(255,195,107,.12);color:#ffdca6")}>
                                <svg width={"17"} height={"17"} viewBox={"0 0 24 24"} fill={"none"} stroke={"#ffc36b"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"} style={sx("flex:none")}>
                                  <path d={sn.d} />
                                </svg>
                                <span style={sx("flex:1;text-align:left;min-width:0;color:#dfe6ff")}>
                                  <span className="sc-interp">{sn.label}</span>
                                </span>
                                {(sn.badge) ? (
                                  <>
                                    <span style={sx("padding:3px 7px;border-radius:20px;background:rgba(255,195,107,.14);color:#ffc36b;font:600 10px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif")}>
                                      <span className="sc-interp">{sn.badgeText}</span>
                                    </span>
                                  </>
                                ) : null}
                              </button>
                            </>
                          ) : null}
                          {(sn.off) ? (
                            <>
                              <button onClick={sn.go} style={sx("display:flex;align-items:center;gap:10px;width:100%;padding:9px 12px;border:none;border-radius:9px;cursor:pointer;font:450 13px/1.5 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;background:transparent;color:#8b95b8")} className={hv("background:rgba(150,170,230,.07);color:#dfe6ff")}>
                                <svg width={"17"} height={"17"} viewBox={"0 0 24 24"} fill={"none"} stroke={"#6f7aa0"} strokeWidth={"2"} strokeLinecap={"round"} strokeLinejoin={"round"} style={sx("flex:none")}>
                                  <path d={sn.d} />
                                </svg>
                                <span style={sx("flex:1;text-align:left;min-width:0;color:inherit")}>
                                  <span className="sc-interp">{sn.label}</span>
                                </span>
                                {(sn.badge) ? (
                                  <>
                                    <span style={sx("padding:3px 7px;border-radius:20px;background:rgba(255,195,107,.14);color:#ffc36b;font:600 10px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif")}>
                                      <span className="sc-interp">{sn.badgeText}</span>
                                    </span>
                                  </>
                                ) : null}
                              </button>
                            </>
                          ) : null}
                        </React.Fragment>
                      ))}
                    </div>
                    <div style={sx("flex:1;min-height:12px")} />
                    <div style={sx("padding:13px;background:rgba(20,25,48,.8);border:1px solid rgba(150,170,230,.14);border-radius:12px;display:flex;flex-direction:column;gap:9px")}>
                      <div style={sx("display:flex;align-items:baseline;justify-content:space-between;gap:8px")}>
                        <span style={sx("font:400 11px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                          <span className="sc-interp">{L.credits}</span>
                        </span>
                        <span style={sx("font:600 15px/1.2 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#ffc36b")}>
                          <span className="sc-interp">{balance}</span>
                        </span>
                      </div>
                      <div style={sx("height:5px;background:rgba(150,170,230,.18);border-radius:4px;overflow:hidden")}>
                        <div style={sx(meterFillStyle)} />
                      </div>
                      <span style={sx("font:400 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0")}>
                        <span className="sc-interp">{L.freeResets}</span>
                      </span>
                    </div>
                    <button onClick={goProfile} style={sx("display:flex;align-items:center;gap:10px;width:100%;padding:9px 10px;background:transparent;border:1px solid rgba(150,170,230,.14);border-radius:12px;cursor:pointer;text-align:left")} className={hv("background:rgba(150,170,230,.07);border-color:rgba(150,180,255,.32)")}>
                      <span style={sx("width:30px;height:30px;flex:none;border-radius:50%;background:linear-gradient(140deg,#ff9f45,#b45cff);display:flex;align-items:center;justify-content:center;font:600 12px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#fff")}>
                        SR
                      </span>
                      <span style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:2px")}>
                        <span style={sx("font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff")}>
                          Sam Rivera
                        </span>
                        <span style={sx("font:400 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad")}>
                          <span className="sc-interp">{L.freePlan}</span>
                        </span>
                      </span>
                      <span style={sx("color:#6f7aa0;font-size:13px")}>
                        ›
                      </span>
                    </button>
                  </div>
                  <div style={sx(deskScreenStyle)}>
                    <div style={sx(starsStyle)} />
                    <div id={"lum-slot-desktop"} style={sx("min-height:100%;position:relative")} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

/** The screen bodies, portaled into whichever slot the active device exposes. */
function PrototypeContent({ v }: { v: any }) {
  const {
    L,
    accountRows,
    addScene,
    afterText,
    balance,
    balanceLeftLabel,
    barBtnsStyle,
    barInnerStyle,
    barStyle,
    boardPadStyle,
    captionStyles,
    costIsMeter,
    costIsPill,
    ctaLabel,
    ctaStyle,
    destinations,
    fmtIdleLabel,
    fmtReadyLabel,
    fmtWorkingLabel,
    formats,
    goBoard,
    goCredits,
    goDeliver,
    goIdentity,
    goOnboard,
    goRecipe,
    goStart,
    hasSelection,
    hashtags,
    isBoard,
    isCredits,
    isDeliver,
    isIdentity,
    isOnboard,
    isProfile,
    isProjects,
    isRecipe,
    isStart,
    ledger,
    memoryKnobStyle,
    memoryToggleStyle,
    meterFillStyle,
    miniWave,
    obDoneLabel,
    obDoneStyle,
    obLine,
    obLineStyle,
    obSteps,
    outLangs,
    packs,
    padStyle,
    palette,
    pendingFillStyle,
    priceRows,
    projects,
    recBtnStyle,
    recHint,
    recIconStyle,
    recProgressStyle,
    recRingStyle,
    recTime,
    recents,
    recipeChips,
    recipes,
    renderAll,
    renderAllLabel,
    renderAllStyle,
    s,
    sceneSummary,
    scenes,
    selCostLabel,
    selText,
    spentFillStyle,
    startIsBar,
    startIsCanvas,
    startPreviewRun,
    toggleMemory,
    toggleRec,
    tryChips,
    upgradeAll,
    waveBars,
  } = v
  return (
    <>
      {(isOnboard) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:620px;margin:0 auto;display:flex;flex-direction:column;gap:20px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("display:flex;gap:6px")}>
                {(obSteps ?? []).map((st: any, i0: number) => (
                  <React.Fragment key={i0}>
                    <span style={sx(st.style)} />
                  </React.Fragment>
                ))}
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:10px")}>
                <span style={sx("font:500 12px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#ffc36b")}>
                  <span className="sc-interp">{L.lastStep}</span>
                </span>
                <h1 style={sx(s.h1)}>
                  <span className="sc-interp">{L.readAloud}</span>
                </h1>
                <p style={sx(s.sub)}>
                  <span className="sc-interp">{L.obSub}</span>
                </p>
              </div>
              <div style={sx("padding:20px;background:linear-gradient(150deg,rgba(30,38,74,.9),rgba(14,18,38,.85));border:1px solid rgba(150,180,255,.22);border-radius:20px;display:flex;flex-direction:column;gap:18px;align-items:center;position:relative;overflow:hidden")}>
                <div style={sx("position:absolute;inset:-50% -20% auto auto;width:280px;height:280px;background:radial-gradient(circle,rgba(255,170,70,.18),transparent 65%);pointer-events:none")} />
                <p style={sx(obLineStyle)}>
                  <span className="sc-interp">{obLine}</span>
                </p>
                <div style={sx("display:flex;align-items:flex-end;justify-content:center;gap:3px;height:56px;width:100%;position:relative")}>
                  {(waveBars ?? []).map((w: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <span style={sx(w.style)} />
                    </React.Fragment>
                  ))}
                </div>
                <div style={sx("display:flex;flex-direction:column;align-items:center;gap:10px;position:relative")}>
                  <button onClick={toggleRec} style={sx(recBtnStyle)}>
                    <span style={sx(recRingStyle)} />
                    <span style={sx(recIconStyle)} />
                  </button>
                  <span style={sx("font:600 15px/1.2 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#ffc36b")}>
                    <span className="sc-interp">{recTime}</span>
                  </span>
                  <span style={sx("font:400 12px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                    <span className="sc-interp">{recHint}</span>
                  </span>
                </div>
                <div style={sx("width:100%;height:5px;border-radius:4px;background:rgba(150,170,230,.16);overflow:hidden;position:relative")}>
                  <div style={sx(recProgressStyle)} />
                </div>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <button onClick={goStart} style={sx(obDoneStyle)}>
                  <span className="sc-interp">{obDoneLabel}</span>
                </button>
                <button onClick={goStart} style={sx("width:100%;height:44px;background:transparent;border:none;border-radius:12px;color:#8b95b8;font:450 13px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer")} className={hv("color:#dfe6ff")}>
                  <span className="sc-interp">{L.skip}</span>
                </button>
              </div>
              <p style={sx("margin:0;font:400 12px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0;text-wrap:pretty")}>
                <span className="sc-interp">{L.privacyNote}</span>
              </p>
            </div>
          </div>
        </>
      ) : null}
      {(isStart) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:20px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <h1 style={sx(s.h1)}>
                  <span className="sc-interp">{L.startTitle}</span>
                </h1>
                <p style={sx(s.sub)}>
                  <span className="sc-interp">{L.startSub}</span>
                </p>
              </div>
              {(startIsCanvas) ? (
                <>
                  <div style={sx("position:relative;border:1.5px dashed rgba(150,180,255,.28);border-radius:20px;background:linear-gradient(180deg,rgba(22,28,54,.75),rgba(12,16,34,.6));padding:22px;display:flex;flex-direction:column;gap:16px;min-height:230px")} className={hv("border-color:rgba(255,190,110,.45)")}>
                    <textarea placeholder={L.canvasPh} style={sx("width:100%;flex:1;min-height:110px;resize:none;background:transparent;border:none;outline:none;color:#eef1fb;font:400 16px/1.9 'IBM Plex Sans','Noto Sans Myanmar',sans-serif")} />
                    <div style={sx("display:grid;grid-template-columns:1fr 1fr;gap:9px")}>
                      <button style={sx("display:flex;align-items:center;justify-content:center;gap:7px;height:46px;padding:0 10px;background:rgba(150,180,255,.10);border:1px solid rgba(150,180,255,.20);border-radius:11px;color:#cfd8f7;font:500 13px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer")} className={hv("background:rgba(150,180,255,.18)")}>
                        <span className="sc-interp">{L.attach}</span>
                      </button>
                      <button style={sx("display:flex;align-items:center;justify-content:center;gap:7px;height:46px;padding:0 10px;background:rgba(150,180,255,.10);border:1px solid rgba(150,180,255,.20);border-radius:11px;color:#cfd8f7;font:500 13px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer")} className={hv("background:rgba(150,180,255,.18)")}>
                        <span className="sc-interp">{L.record}</span>
                      </button>
                    </div>
                    <button onClick={goRecipe} style={sx("display:flex;align-items:center;justify-content:center;gap:8px;width:100%;height:52px;background:linear-gradient(135deg,#ffc36b,#ff8f3d);border:none;border-radius:12px;color:#1a1103;font:600 14.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;box-shadow:0 8px 24px rgba(255,150,60,.28)")} className={hv("filter:brightness(1.07)")}>
                      <span className="sc-interp">{L.cont}</span> →
                    </button>
                  </div>
                </>
              ) : null}
              {(startIsBar) ? (
                <>
                  <div style={sx("display:flex;flex-direction:column;gap:14px")}>
                    <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                      <span style={sx(s.label)}>
                        <span className="sc-interp">{L.pickUp}</span>
                      </span>
                      <div style={sx("display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:11px")}>
                        {(recents ?? []).map((p: any, i0: number) => (
                          <React.Fragment key={i0}>
                            <button onClick={goBoard} style={sx("display:flex;flex-direction:column;gap:9px;padding:11px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:14px;cursor:pointer;text-align:left")} className={hv("border-color:rgba(255,190,110,.4)")}>
                              <span style={sx(p.thumb)} />
                              <span style={sx("font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff;display:block")}>
                                <span className="sc-interp">{p.title}</span>
                              </span>
                              <span style={sx("font:400 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad")}>
                                <span className="sc-interp">{p.meta}</span>
                              </span>
                            </button>
                          </React.Fragment>
                        ))}
                      </div>
                    </div>
                    <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                      <span style={sx(s.label)}>
                        <span className="sc-interp">{L.orNew}</span>
                      </span>
                      <div style={sx("display:flex;align-items:flex-end;gap:9px;padding:10px 10px 10px 16px;background:linear-gradient(180deg,rgba(24,30,58,.95),rgba(14,18,38,.9));border:1px solid rgba(150,180,255,.24);border-radius:18px;box-shadow:0 10px 34px rgba(0,0,0,.35)")}>
                        <button style={sx("width:40px;height:40px;flex:none;border-radius:11px;background:rgba(150,180,255,.12);border:1px solid rgba(150,180,255,.2);color:#cfd8f7;font-size:18px;cursor:pointer")}>
                          ＋
                        </button>
                        <textarea placeholder={L.canvasPh} style={sx("flex:1;min-height:44px;max-height:120px;resize:none;background:transparent;border:none;outline:none;color:#eef1fb;font:400 15px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;padding:9px 0")} />
                        <button onClick={goRecipe} style={sx("width:44px;height:44px;flex:none;border-radius:12px;background:linear-gradient(135deg,#ffc36b,#ff8f3d);border:none;color:#1a1103;font-size:17px;cursor:pointer;box-shadow:0 6px 18px rgba(255,150,60,.3)")} className={hv("filter:brightness(1.07)")}>
                          ↑
                        </button>
                      </div>
                    </div>
                  </div>
                </>
              ) : null}
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.bodySm)}>
                  <span className="sc-interp">{L.tryLabel}</span>
                </span>
                <div style={sx("display:flex;gap:8px;overflow-x:auto;padding-bottom:4px;scrollbar-width:none")}>
                  {(tryChips ?? []).map((c: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <button onClick={goRecipe} style={sx("flex:none;white-space:nowrap;padding:0 14px;background:rgba(150,170,230,.07);border:1px solid rgba(150,170,230,.16);border-radius:20px;color:#b9c3e4;font:400 12.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;height:40px;display:flex;align-items:center")} className={hv("border-color:rgba(255,190,110,.4);color:#fff")}>
                        <span className="sc-interp">{c}</span>
                      </button>
                    </React.Fragment>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </>
      ) : null}
      {(isProjects) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:16px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("display:flex;align-items:center;gap:12px")}>
                <h1 style={sx((s.h2) + ";flex:1;min-width:0")}>
                  <span className="sc-interp">{L.projects}</span>
                </h1>
                <button onClick={goStart} style={sx("display:flex;align-items:center;justify-content:center;gap:7px;height:44px;padding:0 15px;background:linear-gradient(135deg,#ffc36b,#ff8f3d);border:none;border-radius:11px;color:#1a1103;font:600 13px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;flex:none;box-shadow:0 6px 18px rgba(255,150,60,.24)")} className={hv("filter:brightness(1.07)")}>
                  <svg width={"16"} height={"16"} viewBox={"0 0 24 24"} fill={"none"} stroke={"#1a1103"} strokeWidth={"2.4"} strokeLinecap={"round"}>
                    <path d={"M12 5v14M5 12h14"} />
                  </svg>
                  <span className="sc-interp">{L.newShort}</span> 
                </button>
              </div>
              <div style={sx("display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:11px")}>
                {(projects ?? []).map((p: any, i0: number) => (
                  <React.Fragment key={i0}>
                    <button onClick={p.open} style={sx("display:flex;flex-direction:column;gap:0;padding:0;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:15px;cursor:pointer;text-align:left;overflow:hidden")} className={hv("border-color:rgba(255,190,110,.45)")}>
                      <span style={sx(p.thumb)}>
                        <span style={sx(p.pillStyle)}>
                          <span className="sc-interp">{p.state}</span>
                        </span>
                      </span>
                      <span style={sx("display:flex;flex-direction:column;gap:5px;padding:11px 12px 13px")}>
                        <span style={sx("font:500 13px/1.45 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff")}>
                          <span className="sc-interp">{p.title}</span>
                        </span>
                        <span style={sx("font:400 11px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad")}>
                          <span className="sc-interp">{p.meta}</span>
                        </span>
                      </span>
                    </button>
                  </React.Fragment>
                ))}
              </div>
            </div>
          </div>
        </>
      ) : null}
      {(isRecipe) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:18px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("padding:22px;background:linear-gradient(150deg,rgba(30,38,74,.9),rgba(14,18,38,.85));border:1px solid rgba(150,180,255,.22);border-radius:20px;display:flex;flex-direction:column;gap:16px;position:relative;overflow:hidden")}>
                <div style={sx("position:absolute;inset:-40% -30% auto auto;width:280px;height:280px;background:radial-gradient(circle,rgba(255,170,70,.20),transparent 65%);pointer-events:none")} />
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.fromArticle}</span>
                </span>
                <p style={sx(s.plan)}>
                  <span className="sc-interp">{L.planLine}</span>
                </p>
                <div style={sx("display:flex;gap:8px;overflow-x:auto;padding-bottom:4px;position:relative;scrollbar-width:none")}>
                  {(recipeChips ?? []).map((rc: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <span style={sx("flex:none;white-space:nowrap;display:flex;align-items:center;height:36px;padding:0 12px;background:rgba(150,170,230,.09);border:1px solid rgba(150,170,230,.16);border-radius:9px;font:450 12px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                        <span className="sc-interp">{rc}</span>
                      </span>
                    </React.Fragment>
                  ))}
                </div>
                <button style={sx("position:relative;display:flex;align-items:center;justify-content:center;width:100%;height:44px;background:transparent;border:1px dashed rgba(255,190,110,.4);border-radius:11px;font:500 12.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#ffc36b;cursor:pointer")} className={hv("background:rgba(255,195,107,.08)")}>
                  <span className="sc-interp">{L.adjust}</span>
                </button>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.orElse}</span>
                </span>
                <div style={sx("display:flex;flex-direction:column;gap:8px")}>
                  {(recipes ?? []).map((r: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <button onClick={r.pick} style={sx(r.style)}>
                        <span style={sx(r.dot)} />
                        <span style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:4px;text-align:left")}>
                          <span style={sx("font:500 13.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff")}>
                            <span className="sc-interp">{r.name}</span>
                          </span>
                          <span style={sx("font:400 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                            <span className="sc-interp">{r.desc}</span>
                          </span>
                        </span>
                        <span style={sx("font:600 12px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#9aa6cc;flex:none")}>
                          <span className="sc-interp">{r.cost}</span>
                        </span>
                      </button>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <button onClick={startPreviewRun} style={sx("display:flex;align-items:center;justify-content:center;gap:10px;width:100%;padding:16px;background:linear-gradient(135deg,#ffc36b,#ff8f3d);border:none;border-radius:15px;color:#1a1103;font:600 15.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:52px;box-shadow:0 10px 30px rgba(255,150,60,.28)")} className={hv("filter:brightness(1.07)")}>
                 <span className="sc-interp">{L.ctaDraft}</span> 
                <span style={sx("padding:5px 9px;background:rgba(26,17,3,.16);border-radius:20px;font:600 12.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif")}>
                  4 <span className="sc-interp">{L.credits}</span>
                </span>
              </button>
              <p style={sx((s.bodySm) + ";text-align:center")}>
                <span className="sc-interp">{L.reassure}</span>
              </p>
            </div>
          </div>
        </>
      ) : null}
      {(isBoard) ? (
        <>
          <div style={sx("display:flex;flex-direction:column;min-height:100%")}>
            <div style={sx(boardPadStyle)}>
              <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:14px")} data-lum="col">
                <div style={sx("display:flex;align-items:flex-end;justify-content:space-between;gap:14px;flex-wrap:wrap")}>
                  <div style={sx("display:flex;flex-direction:column;gap:6px;min-width:0")}>
                    <h2 style={sx(s.h2)}>
                      Why Webb sees the past
                    </h2>
                    <span style={sx(s.subSm)}>
                      <span className="sc-interp">{sceneSummary}</span>
                    </span>
                  </div>
                  <div style={sx("display:flex;gap:7px")}>
                    <button style={sx("padding:9px 13px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.17);border-radius:10px;color:#c3cbe9;font:500 12.5px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:44px")} className={hv("border-color:rgba(150,180,255,.4)")}>
                      <span className="sc-interp">{L.playAll}</span>
                    </button>
                  </div>
                </div>
                <div style={sx("display:flex;align-items:center;gap:10px;padding:11px 13px;background:linear-gradient(90deg,rgba(110,200,255,.10),rgba(110,200,255,.02));border:1px solid rgba(110,200,255,.2);border-radius:13px")}>
                  <span style={sx("width:7px;height:7px;border-radius:50%;background:#6ec8ff;box-shadow:0 0 10px #6ec8ff;flex:none;animation:lum-pulse 2s ease-in-out infinite")} />
                  <span style={sx(s.noticeStyle)}>
                    <span className="sc-interp">{L.boardBanner}</span>
                  </span>
                </div>
                <div style={sx("display:flex;flex-direction:column;gap:11px")}>
                  {(scenes ?? []).map((s: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <div style={sx(s.cardStyle)}>
                        <div style={sx(s.innerStyle)}>
                          <div style={sx(s.mediaStyle)}>
                            <span style={sx(s.skelStyle)} />
                            <span style={sx("position:absolute;top:6px;left:6px;padding:3px 6px;background:rgba(5,6,15,.72);border-radius:6px;font:600 9.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#dfe6ff")}>
                              <span className="sc-interp">{s.n}</span>
                            </span>
                            <span style={sx(s.badgeStyle)}>
                              <span className="sc-interp">{s.badge}</span>
                            </span>
                            {(s.busy) ? (
                              <>
                                <span style={sx("position:absolute;inset:0;background:rgba(5,6,15,.68);display:flex;align-items:center;justify-content:center")}>
                                  <span style={sx("width:22px;height:22px;border-radius:50%;border:2px solid rgba(255,190,110,.28);border-top-color:#ffc36b;animation:lum-spin .8s linear infinite;display:block")} />
                                </span>
                              </>
                            ) : null}
                          </div>
                          <div style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:9px")}>
                            <p style={sx(s.lineStyle)}>
                              <span className="sc-interp">{s.line}</span>
                            </p>
                            <div style={sx("display:flex;align-items:center;gap:8px;min-width:0")}>
                              <span style={sx(s.captionStyle)}>
                                <span className="sc-interp">{s.caption}</span>
                              </span>
                              <span style={sx("flex:none;font:400 11px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad")}>
                                <span className="sc-interp">{s.time}</span>
                              </span>
                            </div>
                            {(s.busy) ? (
                              <>
                                <div style={sx("display:flex;flex-direction:column;gap:5px")}>
                                  <div style={sx("height:3px;border-radius:3px;background:rgba(150,170,230,.16);overflow:hidden")}>
                                    <div style={sx("width:45%;height:100%;background:linear-gradient(90deg,transparent,#ffc36b,transparent);animation:lum-bar 1.1s ease-in-out infinite")} />
                                  </div>
                                  <span style={sx("font:400 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#ffc36b")}>
                                    <span className="sc-interp">{s.busyLabel}</span>
                                  </span>
                                </div>
                              </>
                            ) : null}
                            <div style={sx("display:flex;gap:7px;padding-top:1px;align-items:center")}>
                              {(s.isReady) ? (
                                <>
                                  <span style={sx("padding:9px 12px;border-radius:9px;font:600 12px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;height:40px;flex:1;min-width:0;justify-content:center;display:flex;align-items:center;background:transparent;border:1px solid rgba(126,224,168,.28);color:#8df0bd")}>
                                    <span className="sc-interp">{s.realLabel}</span>
                                  </span>
                                </>
                              ) : null}
                              {(s.isMarked) ? (
                                <>
                                  <button onClick={s.onUpgrade} style={sx("padding:9px 12px;border-radius:9px;cursor:pointer;font:600 12px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;height:40px;flex:1;min-width:0;justify-content:center;display:flex;align-items:center;background:linear-gradient(135deg,#ffc36b,#ff8f3d);border:none;color:#1a1103")}>
                                    <span className="sc-interp">{s.chosenLabel}</span>
                                  </button>
                                </>
                              ) : null}
                              {(s.isIdle) ? (
                                <>
                                  <button onClick={s.onUpgrade} style={sx("padding:9px 12px;border-radius:9px;cursor:pointer;font:600 12px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;height:40px;flex:1;min-width:0;justify-content:center;display:flex;align-items:center;background:rgba(150,180,255,.10);border:1px solid rgba(150,180,255,.24);color:#dfe6ff")} className={hv("background:rgba(150,180,255,.2);border-color:rgba(150,180,255,.5)")}>
                                    <span className="sc-interp">{s.makeRealLabel}</span>
                                  </button>
                                </>
                              ) : null}
                              <button onClick={s.onMenu} style={sx("width:40px;height:40px;flex:none;border-radius:9px;background:rgba(150,170,230,.07);border:1px solid rgba(150,170,230,.14);color:#9aa6cc;cursor:pointer;font-size:15px;padding:0;line-height:1")} className={hv("color:#fff;border-color:rgba(150,180,255,.4)")}>
                                ⋯
                              </button>
                            </div>
                            {(s.menuOpen) ? (
                              <>
                                <div style={sx("display:grid;grid-template-columns:repeat(auto-fit,minmax(104px,1fr));gap:6px;padding:10px;background:rgba(8,11,24,.7);border:1px solid rgba(150,170,230,.13);border-radius:11px")}>
                                  <button onClick={s.onRegen} style={sx("padding:8px 11px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.15);border-radius:9px;color:#b9c3e4;font:450 11.5px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:38px;display:flex;align-items:center;justify-content:center")} className={hv("color:#fff")}>
                                    <span className="sc-interp">{L.tryAgain}</span>
                                  </button>
                                  <button style={sx("padding:8px 11px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.15);border-radius:9px;color:#b9c3e4;font:450 11.5px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:38px;display:flex;align-items:center;justify-content:center")} className={hv("color:#fff")}>
                                    <span className="sc-interp">{L.changeWords}</span>
                                  </button>
                                  <button onClick={s.onUp} style={sx("padding:8px 11px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.15);border-radius:9px;color:#b9c3e4;font:450 11.5px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:38px;display:flex;align-items:center;justify-content:center")} className={hv("color:#fff")}>
                                    <span className="sc-interp">{L.moveUp}</span>
                                  </button>
                                  <button onClick={s.onDown} style={sx("padding:8px 11px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.15);border-radius:9px;color:#b9c3e4;font:450 11.5px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:38px;display:flex;align-items:center;justify-content:center")} className={hv("color:#fff")}>
                                    <span className="sc-interp">{L.moveDown}</span>
                                  </button>
                                  <button onClick={s.onDelete} style={sx("padding:8px 11px;background:rgba(255,110,110,.07);border:1px solid rgba(255,110,110,.18);border-radius:9px;color:#ff8f8f;font:450 11.5px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:38px;display:flex;align-items:center;justify-content:center")} className={hv("background:rgba(255,110,110,.16)")}>
                                    <span className="sc-interp">{L.remove}</span>
                                  </button>
                                </div>
                              </>
                            ) : null}
                          </div>
                        </div>
                      </div>
                    </React.Fragment>
                  ))}
                </div>
                <button onClick={addScene} style={sx("display:flex;align-items:center;justify-content:center;gap:8px;padding:14px;background:transparent;border:1.5px dashed rgba(150,170,230,.22);border-radius:14px;color:#8b95b8;font:450 13px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:52px")} className={hv("border-color:rgba(255,190,110,.42);color:#ffc36b")}>
                  <span className="sc-interp">{L.addScene}</span>
                </button>
                <div style={sx("height:12px")} />
              </div>
            </div>
            <div style={sx(barStyle)}>
              <div style={sx(barInnerStyle)}>
                {(costIsMeter) ? (
                  <>
                    <div style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:6px")}>
                      <div style={sx("display:flex;align-items:baseline;justify-content:space-between;gap:8px")}>
                        <span style={sx("font:450 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                          <span className="sc-interp">{selText}</span>
                        </span>
                        <span style={sx("font:600 12px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#ffc36b;flex:none")}>
                          <span className="sc-interp">{afterText}</span>
                        </span>
                      </div>
                      <div style={sx("height:6px;border-radius:5px;background:rgba(150,170,230,.16);overflow:hidden;display:flex")}>
                        <div style={sx(spentFillStyle)} />
                        <div style={sx(pendingFillStyle)} />
                      </div>
                    </div>
                  </>
                ) : null}
                {(costIsPill) ? (
                  <>
                    <div style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:4px")}>
                      <span style={sx("font:500 13px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff")}>
                        <span className="sc-interp">{selText}</span>
                      </span>
                      <span style={sx("font:400 11px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                        <span className="sc-interp">{balanceLeftLabel}</span>
                      </span>
                    </div>
                  </>
                ) : null}
                <div style={sx(barBtnsStyle)}>
                  <button onClick={goDeliver} style={sx("display:flex;align-items:center;justify-content:center;height:48px;padding:0 16px;background:transparent;border:1px solid rgba(150,170,230,.2);border-radius:12px;color:#b9c3e4;font:500 13px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer")} className={hv("border-color:rgba(150,180,255,.45);color:#fff")}>
                    <span className="sc-interp">{L.deliverBtn}</span>
                  </button>
                  <button onClick={upgradeAll} style={sx(ctaStyle)}>
                    <span>
                      <span className="sc-interp">{ctaLabel}</span>
                    </span>
                    {(hasSelection) ? (
                      <>
                        <span style={sx("padding:5px 9px;background:rgba(26,17,3,.16);border-radius:20px;font:600 12px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif")}>
                          <span className="sc-interp">{selCostLabel}</span>
                        </span>
                      </>
                    ) : null}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      ) : null}
      {(isDeliver) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:18px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <h1 style={sx(s.h2)}>
                  Why Webb sees the past
                </h1>
                <p style={sx(s.subSm)}>
                  <span className="sc-interp">{L.deliverSub}</span>
                </p>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:11px")}>
                {(formats ?? []).map((f: any, i0: number) => (
                  <React.Fragment key={i0}>
                    <div style={sx(f.cardStyle)}>
                      <div style={sx(f.rowStyle)}>
                        <div style={sx("display:flex;align-items:center;gap:12px;min-width:0;flex:1")}>
                          <span style={sx(f.frameStyle)}>
                            <span style={sx(f.frameFillStyle)} />
                          </span>
                          <span style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:5px")}>
                            <span style={sx("display:flex;align-items:center;gap:8px;min-width:0;flex-wrap:wrap")}>
                              <span style={sx("font:600 14.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#eef1fb")}>
                                <span className="sc-interp">{f.where}</span>
                              </span>
                              <span style={sx((f.tagStyle) + ";flex:none")}>
                                <span className="sc-interp">{f.tag}</span>
                              </span>
                            </span>
                            <span style={sx("font:400 11.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                              <span className="sc-interp">{f.ratio}</span>
                            </span>
                            {(f.rendering) ? (
                              <>
                                <span style={sx("display:flex;flex-direction:column;gap:5px;padding-top:2px")}>
                                  <span style={sx("height:4px;border-radius:3px;background:rgba(150,170,230,.16);overflow:hidden;display:block")}>
                                    <span style={sx(f.progStyle)} />
                                  </span>
                                  <span style={sx("font:400 10.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#ffc36b")}>
                                    <span className="sc-interp">{f.progLabel}</span>
                                  </span>
                                </span>
                              </>
                            ) : null}
                          </span>
                        </div>
                        {(f.isReady) ? (
                          <>
                            <button style={sx((f.btnBase) + ";background:rgba(150,180,255,.12);border:1px solid rgba(150,180,255,.28);color:#dfe6ff")} className={hv("background:rgba(150,180,255,.22)")}>
                              <span className="sc-interp">{fmtReadyLabel}</span>
                            </button>
                          </>
                        ) : null}
                        {(f.rendering) ? (
                          <>
                            <span style={sx((f.btnBase) + ";background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.18);color:#8b95b8")}>
                              <span className="sc-interp">{fmtWorkingLabel}</span>
                            </span>
                          </>
                        ) : null}
                        {(f.isIdle) ? (
                          <>
                            <button onClick={f.action} style={sx((f.btnBase) + ";background:rgba(255,195,107,.10);border:1px solid rgba(255,195,107,.3);color:#ffc36b")} className={hv("background:rgba(255,195,107,.2)")}>
                              <span className="sc-interp">{fmtIdleLabel}</span>
                            </button>
                          </>
                        ) : null}
                      </div>
                    </div>
                  </React.Fragment>
                ))}
              </div>
              <div style={sx("display:flex;align-items:center;gap:11px;padding:13px 14px;background:rgba(110,200,255,.07);border:1px solid rgba(110,200,255,.2);border-radius:14px")}>
                <span style={sx("width:7px;height:7px;border-radius:50%;background:#6ec8ff;box-shadow:0 0 10px #6ec8ff;flex:none;animation:lum-pulse 2s ease-in-out infinite")} />
                <span style={sx(s.noticeStyle)}>
                  <span className="sc-interp">{L.closeNotice}</span>
                </span>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.postTo}</span>
                </span>
                <div style={sx("display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px")}>
                  {(destinations ?? []).map((d: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <button style={sx(d.style)}>
                        <span style={sx(d.dot)} />
                        <span style={sx("color:#c3cbe9")}>
                          <span className="sc-interp">{d.name}</span>
                        </span>
                        <span style={sx("font:400 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad")}>
                          <span className="sc-interp">{d.state}</span>
                        </span>
                      </button>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <div style={sx("padding:16px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:16px;display:flex;flex-direction:column;gap:12px")}>
                <div style={sx("display:flex;align-items:center;gap:10px;flex-wrap:wrap")}>
                  <span style={sx("flex:1;min-width:120px;font:500 13px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                    <span className="sc-interp">{L.yourCaption}</span>
                  </span>
                  <button style={sx("padding:7px 11px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.18);border-radius:9px;color:#c3cbe9;font:450 11.5px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:38px")} className={hv("border-color:rgba(150,180,255,.4)")}>
                    <span className="sc-interp">{L.edit}</span>
                  </button>
                </div>
                <p style={sx("margin:0;font:400 13px/1.7 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#98a2c4;text-wrap:pretty")}>
                  Look far enough into space and you're looking at the past. Here's how Webb turns that into a time machine.
                </p>
                <div style={sx("display:flex;gap:7px;overflow-x:auto;padding-bottom:2px;scrollbar-width:none")}>
                  {(hashtags ?? []).map((h: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <span style={sx("flex:none;white-space:nowrap;display:flex;align-items:center;height:30px;padding:0 11px;background:rgba(150,170,230,.09);border-radius:20px;font:400 11.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                        <span className="sc-interp">{h}</span>
                      </span>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <button onClick={renderAll} style={sx(renderAllStyle)}>
                <span className="sc-interp">{renderAllLabel}</span>
              </button>
            </div>
          </div>
        </>
      ) : null}
      {(isIdentity) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:18px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <h1 style={sx(s.h2)}>
                  <span className="sc-interp">{L.idTitle}</span>
                </h1>
                <p style={sx(s.subSm)}>
                  <span className="sc-interp">{L.idSub}</span>
                </p>
              </div>
              <div style={sx("padding:16px;background:linear-gradient(140deg,rgba(255,170,70,.10),rgba(20,25,48,.8));border:1px solid rgba(255,195,107,.24);border-radius:16px;display:flex;flex-direction:column;gap:14px")}>
                <div style={sx("display:flex;align-items:center;gap:12px;flex-wrap:wrap")}>
                  <span style={sx("width:42px;height:42px;flex:none;border-radius:12px;background:rgba(255,195,107,.14);border:1px solid rgba(255,195,107,.3);display:flex;align-items:center;justify-content:center")}>
                    <span style={sx("display:flex;align-items:flex-end;gap:2px;height:17px")}>
                      {(miniWave ?? []).map((m: any, i0: number) => (
                        <React.Fragment key={i0}>
                          <span style={sx(m)} />
                        </React.Fragment>
                      ))}
                    </span>
                  </span>
                  <span style={sx("flex:1;min-width:120px;display:flex;flex-direction:column;gap:4px")}>
                    <span style={sx("font:600 14px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif")}>
                      <span className="sc-interp">{L.yourVoice}</span>
                    </span>
                    <span style={sx("font:400 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                      <span className="sc-interp">{L.usedIn}</span>
                    </span>
                  </span>
                  <span style={sx("padding:5px 10px;background:rgba(126,224,168,.14);border:1px solid rgba(126,224,168,.3);border-radius:20px;font:600 10.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#8df0bd;flex:none")}>
                    <span className="sc-interp">{L.ready}</span>
                  </span>
                </div>
                <div style={sx("display:grid;grid-template-columns:1fr 1fr;gap:8px")}>
                  <button onClick={goOnboard} style={sx("padding:9px 8px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.18);border-radius:10px;color:#c3cbe9;font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;height:44px;justify-content:center;display:flex;align-items:center;text-align:center")} className={hv("background:rgba(255,195,107,.2)")}>
                    <span className="sc-interp">{L.reRecord}</span>
                  </button>
                  <button style={sx("padding:9px 8px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.18);border-radius:10px;color:#c3cbe9;font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;height:44px;justify-content:center;display:flex;align-items:center;text-align:center")} className={hv("border-color:rgba(150,180,255,.4)")}>
                    <span className="sc-interp">{L.hearSample}</span>
                  </button>
                  <button style={sx("padding:9px 8px;background:transparent;border:1px solid rgba(255,110,110,.22);border-radius:10px;color:#ff8f8f;font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;height:40px;justify-content:center;display:flex;align-items:center;text-align:center;grid-column:1 / -1;border:none;background:transparent")} className={hv("color:#ffb3b3")}>
                    <span className="sc-interp">{L.del}</span>
                  </button>
                </div>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.look}</span>
                </span>
                <div style={sx("padding:16px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:16px;display:flex;flex-direction:column;gap:15px")}>
                  <div style={sx("display:flex;align-items:center;gap:12px;flex-wrap:wrap")}>
                    <span style={sx("flex:1;min-width:96px;font:450 13px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                      <span className="sc-interp">{L.logo}</span>
                    </span>
                    <span style={sx("display:flex;align-items:center;gap:9px")}>
                      <img src={logoUrl} alt={""} style={sx("width:30px;height:30px;display:block")} />
                      <span style={sx("font:400 12px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                        <span className="sc-interp">{L.logoPlace}</span>
                      </span>
                    </span>
                  </div>
                  <div style={sx("height:1px;background:rgba(150,170,230,.1)")} />
                  <div style={sx("display:flex;align-items:center;gap:12px;flex-wrap:wrap")}>
                    <span style={sx("flex:1;min-width:96px;font:450 13px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                      <span className="sc-interp">{L.palette}</span>
                    </span>
                    <span style={sx("display:flex;gap:6px")}>
                      {(palette ?? []).map((c: any, i0: number) => (
                        <React.Fragment key={i0}>
                          <span style={sx(c)} />
                        </React.Fragment>
                      ))}
                    </span>
                  </div>
                  <div style={sx("height:1px;background:rgba(150,170,230,.1)")} />
                  <div style={sx("display:flex;align-items:center;gap:12px;flex-wrap:wrap")}>
                    <span style={sx("flex:1;min-width:96px;font:450 13px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                      <span className="sc-interp">{L.type}</span>
                    </span>
                    <span style={sx("font:500 13.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                      Space Grotesk · IBM Plex Sans
                    </span>
                  </div>
                  <div style={sx("height:1px;background:rgba(150,170,230,.1)")} />
                  <div style={sx("display:flex;align-items:center;gap:12px;flex-wrap:wrap")}>
                    <span style={sx("flex:1;min-width:96px;font:450 13px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                      <span className="sc-interp">{L.introOutro}</span>
                    </span>
                    <span style={sx("font:400 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                      <span className="sc-interp">{L.stingVal}</span>
                    </span>
                  </div>
                </div>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.captionStyle}</span>
                </span>
                <div style={sx("display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px")}>
                  {(captionStyles ?? []).map((cs: any, i0: number) => (
                    <React.Fragment key={i0}>
                      {(cs.on) ? (
                        <>
                          <button onClick={cs.pick} style={sx("display:flex;flex-direction:column;gap:9px;align-items:flex-start;padding:13px;border-radius:14px;cursor:pointer;text-align:left;background:rgba(255,195,107,.10);border:1px solid rgba(255,195,107,.42)")}>
                            <span style={sx(cs.previewStyle)}>
                              <span className="sc-interp">{cs.sample}</span>
                            </span>
                            <span style={sx("font:500 12px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#ffc36b")}>
                              <span className="sc-interp">{cs.name}</span>
                            </span>
                          </button>
                        </>
                      ) : null}
                      {(cs.off) ? (
                        <>
                          <button onClick={cs.pick} style={sx("display:flex;flex-direction:column;gap:9px;align-items:flex-start;padding:13px;border-radius:14px;cursor:pointer;text-align:left;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14)")} className={hv("border-color:rgba(150,180,255,.4)")}>
                            <span style={sx(cs.previewStyle)}>
                              <span className="sc-interp">{cs.sample}</span>
                            </span>
                            <span style={sx("font:450 12px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                              <span className="sc-interp">{cs.name}</span>
                            </span>
                          </button>
                        </>
                      ) : null}
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.videoLang}</span>
                </span>
                <div style={sx("padding:14px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:16px;display:flex;flex-direction:column;gap:12px")}>
                  <span style={sx(s.bodySm)}>
                    <span className="sc-interp">{L.videoLangHelp}</span>
                  </span>
                  <div style={sx("display:grid;grid-template-columns:repeat(auto-fit,minmax(132px,1fr));gap:8px")}>
                    {(outLangs ?? []).map((ol: any, i0: number) => (
                      <React.Fragment key={i0}>
                        {(ol.on) ? (
                          <>
                            <button onClick={ol.pick} style={sx("display:flex;align-items:center;gap:8px;width:100%;height:46px;padding:0 12px;border-radius:11px;cursor:pointer;text-align:left;background:rgba(255,195,107,.12);border:1px solid rgba(255,195,107,.45)")}>
                              <span style={sx("width:16px;height:16px;flex:none;border-radius:50%;background:linear-gradient(135deg,#ffc36b,#ff8f3d);display:flex;align-items:center;justify-content:center;font:700 9px/1 'IBM Plex Sans',sans-serif;color:#1a1103")}>
                                ✓
                              </span>
                              <span style={sx(ol.labelStyle)}>
                                <span className="sc-interp">{ol.name}</span>
                              </span>
                            </button>
                          </>
                        ) : null}
                        {(ol.off) ? (
                          <>
                            <button onClick={ol.pick} style={sx("display:flex;align-items:center;gap:8px;width:100%;height:46px;padding:0 12px;border-radius:11px;cursor:pointer;text-align:left;background:rgba(150,170,230,.06);border:1px solid rgba(150,170,230,.16)")} className={hv("border-color:rgba(150,180,255,.45)")}>
                              <span style={sx("width:16px;height:16px;flex:none;border-radius:50%;border:1px solid rgba(150,170,230,.35);display:block")} />
                              <span style={sx(ol.labelStyle)}>
                                <span className="sc-interp">{ol.name}</span>
                              </span>
                            </button>
                          </>
                        ) : null}
                      </React.Fragment>
                    ))}
                  </div>
                </div>
              </div>
              <div style={sx("padding:16px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:16px;display:flex;align-items:center;gap:12px;flex-wrap:wrap")}>
                <span style={sx("flex:1;min-width:160px;display:flex;flex-direction:column;gap:4px")}>
                  <span style={sx("font:500 13.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff")}>
                    <span className="sc-interp">{L.seriesMem}</span>
                  </span>
                  <span style={sx("font:400 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                    <span className="sc-interp">{L.seriesSub}</span>
                  </span>
                </span>
                <button onClick={toggleMemory} style={sx(memoryToggleStyle)}>
                  <span style={sx(memoryKnobStyle)} />
                </button>
              </div>
            </div>
          </div>
        </>
      ) : null}
      {(isCredits) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:18px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("padding:20px;background:linear-gradient(150deg,rgba(30,38,74,.9),rgba(14,18,38,.85));border:1px solid rgba(150,180,255,.22);border-radius:20px;display:flex;flex-direction:column;gap:14px;position:relative;overflow:hidden")}>
                <div style={sx("position:absolute;inset:-50% -25% auto auto;width:280px;height:280px;background:radial-gradient(circle,rgba(255,170,70,.2),transparent 65%);pointer-events:none")} />
                <span style={sx("font:400 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc;position:relative")}>
                  <span className="sc-interp">{L.balance}</span>
                </span>
                <div style={sx("display:flex;align-items:baseline;gap:9px;position:relative;flex-wrap:wrap")}>
                  <span style={sx("font:600 clamp(34px,5vw,46px)/1.15 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#ffc36b;letter-spacing:-.02em")}>
                    <span className="sc-interp">{balance}</span>
                  </span>
                  <span style={sx("font:400 14px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                    <span className="sc-interp">{L.credits}</span>
                  </span>
                </div>
                <div style={sx("height:7px;border-radius:5px;background:rgba(150,170,230,.16);overflow:hidden;position:relative")}>
                  <div style={sx(meterFillStyle)} />
                </div>
                <span style={sx("font:400 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc;position:relative")}>
                  <span className="sc-interp">{L.freeLine}</span>
                </span>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.costHeading}</span>
                </span>
                <div style={sx("display:flex;flex-direction:column;gap:1px;border-radius:16px;overflow:hidden;border:1px solid rgba(150,170,230,.14)")}>
                  {(priceRows ?? []).map((pr: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <div style={sx("display:flex;align-items:center;gap:12px;padding:13px 15px;background:rgba(20,25,48,.75);border-bottom:1px solid rgba(150,170,230,.09)")}>
                        <span style={sx("flex:1;min-width:0;font:450 13px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9")}>
                          <span className="sc-interp">{pr.label}</span>
                        </span>
                        <span style={sx(pr.costStyle)}>
                          <span className="sc-interp">{pr.cost}</span>
                        </span>
                      </div>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.recent}</span>
                </span>
                <div style={sx("display:flex;flex-direction:column;gap:1px;border-radius:16px;overflow:hidden;border:1px solid rgba(150,170,230,.14)")}>
                  {(ledger ?? []).map((lg: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <div style={sx("display:flex;align-items:center;gap:12px;padding:13px 15px;background:rgba(20,25,48,.75);border-bottom:1px solid rgba(150,170,230,.09)")}>
                        <span style={sx(lg.dot)} />
                        <span style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:3px")}>
                          <span style={sx("font:450 13px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff")}>
                            <span className="sc-interp">{lg.what}</span>
                          </span>
                          <span style={sx("font:400 11px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#7d88ad")}>
                            <span className="sc-interp">{lg.when}</span>
                          </span>
                        </span>
                        <span style={sx(lg.amtStyle)}>
                          <span className="sc-interp">{lg.amt}</span>
                        </span>
                      </div>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.topUp}</span>
                </span>
                <div style={sx("display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px")}>
                  {(packs ?? []).map((pk: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <button onClick={pk.buy} style={sx(pk.style)} className={hv("border-color:rgba(255,195,107,.5)")}>
                        <span style={sx("display:flex;align-items:center;gap:7px;flex-wrap:wrap")}>
                          <span style={sx("font:600 19px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#eef1fb")}>
                            <span className="sc-interp">{pk.credits}</span>
                          </span>
                          {(pk.best) ? (
                            <>
                              <span style={sx("padding:3px 8px;border-radius:20px;background:rgba(126,224,168,.15);border:1px solid rgba(126,224,168,.3);font:600 10px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#8df0bd")}>
                                <span className="sc-interp">{L.bestValue}</span>
                              </span>
                            </>
                          ) : null}
                        </span>
                        <span style={sx("font:400 12px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                          <span className="sc-interp">{pk.price}</span>
                        </span>
                      </button>
                    </React.Fragment>
                  ))}
                </div>
                <p style={sx("margin:0;font:400 12px/1.6 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0;text-wrap:pretty")}>
                  <span className="sc-interp">{L.noSub}</span>
                </p>
              </div>
            </div>
          </div>
        </>
      ) : null}
      {(isProfile) ? (
        <>
          <div style={sx(padStyle)}>
            <div style={sx("max-width:680px;margin:0 auto;display:flex;flex-direction:column;gap:18px;animation:lum-rise .35s ease both")} data-lum="col">
              <div style={sx("display:flex;align-items:center;gap:15px;padding:18px;background:linear-gradient(150deg,rgba(30,38,74,.9),rgba(14,18,38,.85));border:1px solid rgba(150,180,255,.2);border-radius:20px;position:relative;overflow:hidden;flex-wrap:wrap")}>
                <div style={sx("position:absolute;inset:-60% -20% auto auto;width:260px;height:260px;background:radial-gradient(circle,rgba(180,92,255,.22),transparent 65%);pointer-events:none")} />
                <span style={sx("width:62px;height:62px;flex:none;border-radius:50%;background:linear-gradient(140deg,#ff9f45,#b45cff);display:flex;align-items:center;justify-content:center;font:600 22px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#fff;box-shadow:0 0 0 2px rgba(255,255,255,.1),0 8px 24px rgba(180,92,255,.3);position:relative")}>
                  SR
                </span>
                <div style={sx("flex:1;min-width:140px;display:flex;flex-direction:column;gap:6px;position:relative")}>
                  <span style={sx("font:600 19px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;letter-spacing:-.015em")}>
                    Sam Rivera
                  </span>
                  <span style={sx("font:400 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                    <span className="sc-interp">{L.published}</span>
                  </span>
                </div>
                <button style={sx("padding:9px 13px;background:rgba(150,170,230,.09);border:1px solid rgba(150,170,230,.2);border-radius:10px;color:#c3cbe9;font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:44px;position:relative;flex:none")} className={hv("border-color:rgba(150,180,255,.45);color:#fff")}>
                  <span className="sc-interp">{L.edit}</span>
                </button>
              </div>
              <div style={sx("display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:11px")}>
                <button onClick={goCredits} style={sx("flex:1;min-width:150px;padding:15px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:15px;display:flex;flex-direction:column;gap:9px;cursor:pointer;text-align:left")} className={hv("border-color:rgba(255,190,110,.4)")}>
                  <span style={sx("display:flex;align-items:baseline;justify-content:space-between;gap:8px")}>
                    <span style={sx("font:400 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                      <span className="sc-interp">{L.credits}</span>
                    </span>
                    <span style={sx("font:600 20px/1.2 'Space Grotesk','Noto Sans Myanmar',sans-serif;color:#ffc36b;flex:none")}>
                      <span className="sc-interp">{balance}</span>
                    </span>
                  </span>
                  <span style={sx("height:6px;background:rgba(150,170,230,.18);border-radius:5px;overflow:hidden;display:block")}>
                    <span style={sx(meterFillStyle)} />
                  </span>
                  <span style={sx("font:400 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0")}>
                    <span className="sc-interp">{L.freeResets}</span>
                  </span>
                </button>
                <div style={sx("flex:1;min-width:150px;padding:15px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14);border-radius:15px;display:flex;flex-direction:column;gap:7px;justify-content:center")}>
                  <span style={sx("font:400 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8")}>
                    <span className="sc-interp">{L.thisMonth}</span>
                  </span>
                  <span style={sx("font:600 20px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif")}>
                    <span className="sc-interp">{L.nShorts}</span>
                  </span>
                  <span style={sx("font:400 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#6f7aa0")}>
                    <span className="sc-interp">{L.across}</span>
                  </span>
                </div>
              </div>
              <button onClick={goIdentity} style={sx("display:flex;align-items:center;gap:14px;padding:16px;background:linear-gradient(140deg,rgba(255,170,70,.10),rgba(20,25,48,.8));border:1px solid rgba(255,195,107,.24);border-radius:16px;cursor:pointer;text-align:left")} className={hv("border-color:rgba(255,195,107,.5)")}>
                <span style={sx("width:42px;height:42px;flex:none;border-radius:12px;background:rgba(255,195,107,.14);border:1px solid rgba(255,195,107,.3);display:flex;align-items:center;justify-content:center")}>
                  <span style={sx("display:flex;align-items:flex-end;gap:2px;height:17px")}>
                    {(miniWave ?? []).map((m: any, i0: number) => (
                      <React.Fragment key={i0}>
                        <span style={sx(m)} />
                      </React.Fragment>
                    ))}
                  </span>
                </span>
                <span style={sx("flex:1;min-width:0;display:flex;flex-direction:column;gap:4px")}>
                  <span style={sx("font:600 14px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#eef1fb")}>
                    <span className="sc-interp">{L.idTitle}</span>
                  </span>
                  <span style={sx("font:400 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#9aa6cc")}>
                    <span className="sc-interp">{L.voiceReady}</span>
                  </span>
                </span>
                <span style={sx("color:#6f7aa0;font-size:15px;flex:none")}>
                  ›
                </span>
              </button>
              <div style={sx("display:flex;flex-direction:column;gap:9px")}>
                <span style={sx(s.label)}>
                  <span className="sc-interp">{L.account}</span>
                </span>
                <div style={sx("display:flex;flex-direction:column;gap:1px;border-radius:16px;overflow:hidden;border:1px solid rgba(150,170,230,.14)")}>
                  {(accountRows ?? []).map((row: any, i0: number) => (
                    <React.Fragment key={i0}>
                      <button style={sx("display:flex;align-items:center;gap:12px;width:100%;padding:14px 15px;background:rgba(20,25,48,.75);border:none;border-bottom:1px solid rgba(150,170,230,.09);cursor:pointer;text-align:left;min-height:52px")} className={hv("background:rgba(30,36,68,.9)")}>
                        <span style={sx("flex:1;min-width:0;font:450 13.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#e6ebff")}>
                          <span className="sc-interp">{row.label}</span>
                        </span>
                        <span style={sx("font:400 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#8b95b8;flex:none")}>
                          <span className="sc-interp">{row.value}</span>
                        </span>
                        <span style={sx("color:#5f6a8e;font-size:14px;flex:none")}>
                          ›
                        </span>
                      </button>
                    </React.Fragment>
                  ))}
                </div>
              </div>
              <button style={sx("padding:14px;background:transparent;border:1px solid rgba(255,110,110,.24);border-radius:13px;color:#ff8f8f;font:500 13px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;cursor:pointer;min-height:52px")} className={hv("background:rgba(255,110,110,.08);border-color:rgba(255,110,110,.45)")}>
                <span className="sc-interp">{L.signOut}</span>
              </button>
            </div>
          </div>
        </>
      ) : null}
    </>
  )
}

export function PrototypeShell({ v }: { v: any }) {
  const [slot, setSlot] = React.useState<HTMLElement | null>(null)

  // The chrome has to be in the DOM before its slot can be found, so this runs after
  // layout, and again whenever the device switches between the phone and desktop shells.
  React.useLayoutEffect(() => {
    setSlot(document.getElementById(v.isPhone ? 'lum-slot-phone' : 'lum-slot-desktop'))
  }, [v.isPhone])

  return (
    <>
      <PrototypeChrome v={v} />
      {slot ? createPortal(<PrototypeContent v={v} />, slot) : null}
    </>
  )
}
