// @ts-nocheck
/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Design-prototype behaviour, as a hook.
 *
 * GENERATED by apps/web/scripts/convert-prototype.py — do not hand-edit.
 *
 * Fake scenes, fake credits, fake render progress — the mock the design was drawn against.
 * It lets the UI be checked against the design before anything is wired to the API, and it
 * is NOT the product's data shape: the real storyboard comes from the backend Plan/Scene
 * model. The prototype's class component becomes a hook here; its derived bindings are
 * carried over unchanged so the rendered output matches the design.
 *
 * `@ts-nocheck` is deliberate and scoped to this one generated file. It is a port of design
 * tool JavaScript — optional arguments, dynamically indexed literals — and type-checking it
 * buys nothing: nothing imports its internal types, and its correctness is established by
 * comparing the rendered result against the design. PrototypeShell.tsx, which is where a
 * missing binding would actually break, stays fully type-checked under the app's strict
 * settings, as does every hand-written file.
 */
import { useCallback, useEffect, useRef, useState } from 'react'

import { LINES, MY, SCREENS, TITLES } from './data'

export type MockProps = {
  screen?: string
  startVariant?: string
  cardVariant?: string
  costVariant?: string
  backdrop?: string
  lang?: string
}

export function useLuminaMock(props: MockProps = {}) {
  const [state, setState] = useState<any>(() => ({
    screen: props.screen ?? "start",
    device: "desktop",
    startVariant: props.startVariant ?? "canvas",
    cardVariant: props.cardVariant ?? "filmstrip",
    costVariant: props.costVariant ?? "meter",
    backdrop: props.backdrop ?? "nebula",
    memory: true,
    recording: false,
    recSecs: 0,
    capStyle: "pop",
    openMenu: null,
    lang: props.lang ?? "en",
    outLang: "en",
    balance: 128,
    formats: { "9:16": "ready", "1:1": "idle", "16:9": "idle" },
    fmtProg: { "9:16": 100, "1:1": 0, "16:9": 0 },
    scenes: LINES.map((l, i) => ({
      id: i, line: l[0], caption: l[1], time: l[2], media: l[3],
      status: i === 1 ? "ready" : "preview", busy: false, sel: false, loaded: i !== 4
    }))
  }))

  const timers = useRef<ReturnType<typeof setTimeout>[]>([])
  const recTimer = useRef<ReturnType<typeof setInterval> | null>(null)

  const track = (t: ReturnType<typeof setTimeout>) => {
    timers.current.push(t)
    return t
  }

  const stopRec = () => {
    if (recTimer.current !== null) {
      clearInterval(recTimer.current)
      recTimer.current = null
    }
  }

  /** Mirrors React class setState: an updater returning null means "no change". */
  const set = useCallback((patch: any) => {
    setState((s: any) => {
      const next = typeof patch === 'function' ? patch(s) : patch
      return next ? { ...s, ...next } : s
    })
  }, [])

  const go = useCallback((screen: string) => set({ screen }), [set])

  // The prototype reveals scene 5's media after a beat, to show the loading state.
  useEffect(() => {
    const running = timers
    running.current.push(
      setTimeout(
        () => set((s: any) => ({
          scenes: s.scenes.map((x: any) => (x.id === 4 ? { ...x, loaded: true } : x)),
        })),
        2600,
      ),
    )
    return () => {
      running.current.forEach(clearTimeout)
      stopRec()
    }
  }, [set])

  const toggleRec = () => {
    if (state.recording) {
      stopRec();
      set({ recording: false });
    } else {
      set({ recording: true });
      recTimer.current = setInterval(() => {
        set((s: any) => {
          const n = s.recSecs + 1;
          if (n >= 62) { stopRec(); return { recSecs: 62, recording: false }; }
          return { recSecs: n };
        });
      }, 130);
    }
  }

  const regen = (id: any) => {
    set((s: any) => ({ scenes: s.scenes.map((x: any) => x.id === id ? { ...x, busy: true } : x) }));
    track(setTimeout(() => set((s: any) => ({
      scenes: s.scenes.map((x: any) => x.id === id ? { ...x, busy: false } : x)
    })), 2100));
  }

  const toggleSel = (id: any) => {
    set((s: any) => ({ scenes: s.scenes.map((x: any) => x.id === id ? { ...x, sel: x.status === "ready" ? x.sel : !x.sel } : x) }));
  }

  const move = (id: any, dir: any) => {
    set((s: any) => {
      const a = s.scenes.slice(), i = a.findIndex((x: any) => x.id === id), j = i + dir;
      if (j < 0 || j >= a.length) return null;
      const t = a[i]; a[i] = a[j]; a[j] = t;
      return { scenes: a };
    });
  }

  const del = (id: any) => { set((s: any) => ({ scenes: s.scenes.filter((x: any) => x.id !== id) })); }

  const addScene = () => {
    set((s: any) => ({
      scenes: s.scenes.concat([{
        id: Date.now(), line: "New scene — write the line you want narrated here.",
        caption: "New scene", time: "—", media: "linear-gradient(150deg,#26305c,#0b0f22 72%)",
        status: "preview", busy: false, sel: false, loaded: true
      }])
    }));
  }

  const runUpgrade = () => {
    const ids = state.scenes.filter((x: any) => x.sel).map((x: any) => x.id);
    if (!ids.length) return;
    set((s: any) => ({
      balance: s.balance - ids.length * 15,
      scenes: s.scenes.map((x: any) => x.sel ? { ...x, busy: true, sel: false } : x)
    }));
    ids.forEach((id: any, k: any) => track(setTimeout(() => set((s: any) => ({
      scenes: s.scenes.map((x: any) => x.id === id ? { ...x, busy: false, status: "ready" } : x)
    })), 1400 + k * 900)));
  }

  const render1 = (ratio: any) => {
    if (state.formats[ratio] !== "idle") return;
    set((s: any) => ({ formats: { ...s.formats, [ratio]: "rendering" }, fmtProg: { ...s.fmtProg, [ratio]: 8 } }));
    const tick = setInterval(() => {
      set((s: any) => {
        const p = s.fmtProg[ratio] + 9;
        if (p >= 100) {
          clearInterval(tick);
          return { formats: { ...s.formats, [ratio]: "ready" }, fmtProg: { ...s.fmtProg, [ratio]: 100 } };
        }
        return { fmtProg: { ...s.fmtProg, [ratio]: p } };
      });
    }, 220);
  }

  const renderAll = () => { ["1:1", "16:9", "9:16"].forEach((r: any) => render1(r)); }

  const seg = (a: boolean) =>
    "padding:8px 12px;border:none;border-radius:8px;cursor:pointer;white-space:nowrap;font:500 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;transition:.15s;" +
    (a ? "background:linear-gradient(135deg,#ffc36b,#ff8f3d);color:#1a1103" : "background:transparent;color:#8b95b8")

  const segSm = (a: boolean) =>
    "padding:6px 10px;border:none;border-radius:7px;cursor:pointer;white-space:nowrap;font:500 11.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;transition:.15s;" +
    (a ? "background:rgba(150,180,255,.22);color:#e9efff" : "background:transparent;color:#7d88ad")


    const st = state;
    const phone = st.device === "phone";
    const nebula = st.backdrop === "nebula";
    const cinema = st.cardVariant === "cinema";
    const scr = st.screen;
    const my = st.lang === "my";
    const t = (en: any, key: any) => (my && MY[key] !== undefined ? MY[key] : en);
    const cr = (n: any) => n + " " + (my ? MY.credits : (n === 1 ? "credit" : "credits"));
    const meta = (ep: any, n: any, unit: any) => my
      ? MY.ep + " " + ep + " · " + n + " " + (unit === "w" ? MY.wAgo : MY.dAgo)
      : "Episode " + ep + " · " + n + (unit === "w" ? (n === 1 ? " week" : " weeks") : (n === 1 ? " day" : " days")) + " ago";
    // Myanmar stacks marks above and below the baseline — it needs far more leading than Latin.
    const lh = my ? 2.05 : 1.6;
    const lhTight = my ? 1.75 : 1.3;
    const fam = my ? "'Noto Sans Myanmar','IBM Plex Sans','Noto Sans Myanmar',sans-serif" : "'IBM Plex Sans','Noto Sans Myanmar',sans-serif";
    const famHead = my ? "'Noto Sans Myanmar','Space Grotesk','Noto Sans Myanmar',sans-serif" : "'Space Grotesk','Noto Sans Myanmar',sans-serif";
    const body = (size: any, color: any, weight: any) => "font:" + (weight || 400) + " " + size + "px/" + lh + " " + fam + ";color:" + color + ";margin:0;text-wrap:pretty";
    const btnFont = "font:600 " + (my ? 13 : 14) + "px/" + lhTight + " " + fam + ";";
    const sel = st.scenes.filter((s: any) => s.sel);
    const selCost = sel.length * 15;
    const spentPct = Math.max(0, Math.min(100, ((200 - st.balance) / 200) * 100));
    const pendPct = Math.min(100 - spentPct, (selCost / 200) * 100);
    const readyN = st.scenes.filter((s: any) => s.status === "ready").length;
    const recPct = Math.min(100, (st.recSecs / 60) * 100);
    const recDone = st.recSecs >= 60;

    const navItems = [
      ["onboard", "Onboarding"], ["start", "Start"], ["projects", "Projects"], ["recipe", "Recipe"], ["board", "Storyboard"],
      ["deliver", "Deliver"], ["identity", "Identity"], ["credits", "Credits"], ["profile", "Profile"]
    // top bar stays English — it is the mockup's own chrome, not the product UI
    ].map(([id, label]: any) => ({ label, on: scr === id, off: scr !== id, go: () => go(id) }));

    const langOpts = [
      { label: "English", on: !my, off: my, go: () => set({ lang: "en" }) },
      { label: "မြန်မာ", on: my, off: !my, go: () => set({ lang: "my" }) }
    ];

    const mkOpt = (label: any, on: any, fn: any) => ({ label, on, off: !on, go: fn });
    const variantGroups = [
      { label: "Language", opts: langOpts },
      { label: "Backdrop", opts: [mkOpt("Universe", nebula, () => set({ backdrop: "nebula" })), mkOpt("Deep dark", !nebula, () => set({ backdrop: "void" }))] },
      { label: "Start input", opts: [mkOpt("Canvas", st.startVariant === "canvas", () => set({ startVariant: "canvas" })), mkOpt("Prompt bar", st.startVariant === "bar", () => set({ startVariant: "bar" }))] },
      { label: "Scene card", opts: [mkOpt("Filmstrip", !cinema, () => set({ cardVariant: "filmstrip" })), mkOpt("Cinema", cinema, () => set({ cardVariant: "cinema" }))] },
      { label: "Cost", opts: [mkOpt("Fuel meter", st.costVariant === "meter", () => set({ costVariant: "meter" })), mkOpt("Inline pill", st.costVariant === "pill", () => set({ costVariant: "pill" }))] }
    ];

    const ICON = {
      spark: "M12 3v18M3 12h18M6.5 6.5l11 11M17.5 6.5l-11 11",
      grid: "M4 5h6v6H4zM14 5h6v6h-6zM4 15h6v4H4zM14 15h6v4h-6z",
      // credits are tokens, not currency — a coin with a spark, no dollar sign
      coin: "M12 3.2a8.8 8.8 0 100 17.6 8.8 8.8 0 000-17.6zM12 7.6l1.15 3.25L16.4 12l-3.25 1.15L12 16.4l-1.15-3.25L7.6 12l3.25-1.15z",
      user: "M12 12a4 4 0 100-8 4 4 0 000 8zM4.5 20a7.5 7.5 0 0115 0",
      film: "M4 4h16v16H4zM4 9h16M4 15h16M9 4v16M15 4v16",
      send: "M4 12l16-8-6 8 6 8z",
      wand: "M4 20L16 8M15 3l1.2 2.6L19 7l-2.4 1.4L15 11l-1.2-2.6L11 7l2.6-1.4zM19 14l.8 1.7 1.9.9-1.9.9-.8 1.7-.8-1.7-1.9-.9 1.9-.9z",
      mic: "M12 3a3 3 0 013 3v6a3 3 0 01-6 0V6a3 3 0 013-3zM5 11a7 7 0 0014 0M12 18v3"
    };
    const tabs = [
      ["start", t("Create", "tabCreate"), ICON.spark],
      ["projects", t("Projects", "tabProjects"), ICON.grid],
      ["credits", t("Credits", "tabCredits"), ICON.coin],
      ["profile", t("You", "tabYou"), ICON.user]
    ].map(([id, label, d]: any) => ({
      label, d, go: () => go(id),
      on: scr === id || (id === "projects" && (scr === "board" || scr === "recipe" || scr === "deliver")),
      off: !(scr === id || (id === "projects" && (scr === "board" || scr === "recipe" || scr === "deliver")))
    }));

    const sideNav = [
      ["projects", t("Projects", "tabProjects"), ICON.grid, false, ""],
      ["board", t("Storyboard", "sideBoard"), ICON.film, true, String(st.scenes.length)],
      ["deliver", t("Deliver", "sideDeliver"), ICON.send, false, ""],
      ["identity", t("Identity kit", "sideIdentity"), ICON.wand, false, ""],
      ["credits", t("Credits", "sideCredits"), ICON.coin, false, ""],
      ["onboard", t("Voice setup", "sideVoice"), ICON.mic, false, ""]
    ].map(([id, label, d, badge, badgeText]: any) => ({
      label, badge, badgeText, d, go: () => go(id),
      on: scr === id, off: scr !== id
    }));

    const waveBars = Array.from({ length: 30 }, (_: any, i: any) => {
      const active = st.recording || st.recSecs > 0;
      const reached = (i / 30) * 100 < recPct;
      const h = 10 + Math.abs(Math.sin(i * 1.31)) * 34;
      return {
        style: "width:4px;border-radius:3px;flex:none;display:block;height:" + h.toFixed(0) + "px;transform-origin:bottom;" +
          (reached ? "background:linear-gradient(180deg,#ffc36b,#ff8f3d);" : "background:rgba(150,170,230,.2);") +
          (st.recording && !reached ? "animation:lum-eq " + (0.5 + (i % 5) * 0.11).toFixed(2) + "s ease-in-out infinite;" : (active ? "" : ""))
      };
    });

    const CAPS = {
      en: ["Light is fast", "'Space Grotesk',sans-serif", "'IBM Plex Sans',sans-serif"],
      my: ["အလင်းက မြန်တယ်", "'Noto Sans Myanmar',sans-serif", "'Noto Sans Myanmar',sans-serif"],
      ja: ["光は速い", "'Noto Sans JP',sans-serif", "'Noto Sans JP',sans-serif"],
      ko: ["빛은 빠릅니다", "'Noto Sans KR',sans-serif", "'Noto Sans KR',sans-serif"],
      zh: ["光速很快", "'Noto Sans SC',sans-serif", "'Noto Sans SC',sans-serif"],
      th: ["แสงเร็วมาก", "'Noto Sans Thai',sans-serif", "'Noto Sans Thai',sans-serif"],
      vi: ["Ánh sáng rất nhanh", "'Space Grotesk',sans-serif", "'IBM Plex Sans',sans-serif"],
      tl: ["Mabilis ang liwanag", "'Space Grotesk',sans-serif", "'IBM Plex Sans',sans-serif"]
    };
    const capSample = CAPS[st.outLang][0];
    const capHead = CAPS[st.outLang][1], capBody = CAPS[st.outLang][2];
    const capLh = (st.outLang === "my" || st.outLang === "th") ? 2.1 : 1.5;
    const capStyles = [
      { id: "pop", name: t("Bold pop", "capPop"), sample: capSample, css: "font:700 13px/" + capLh + " " + capHead + ";color:#1a1103;background:#ffc36b;padding:7px 10px;border-radius:7px" },
      { id: "clean", name: t("Clean line", "capClean"), sample: capSample, css: "font:500 13px/" + capLh + " " + capBody + ";color:#fff;background:rgba(5,6,15,.7);padding:7px 10px;border-radius:7px" },
      { id: "glow", name: t("Soft glow", "capGlow"), sample: capSample, css: "font:600 13px/" + capLh + " " + capHead + ";color:#fff;text-shadow:0 0 12px rgba(120,180,255,.9);padding:7px 10px" }
    ].map((c: any) => ({
      name: c.name, sample: c.sample, pick: () => set({ capStyle: c.id }),
      on: st.capStyle === c.id, off: st.capStyle !== c.id,
      previewStyle: c.css + ";display:inline-block;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap"
    }));

    const fmtMeta = {
      "9:16": [t("Tall", "fTall"), "TikTok, Reels & Shorts", 34, 60],
      "1:1": [t("Square", "fSquare"), "Instagram", 50, 50],
      "16:9": [t("Wide", "fWide"), "YouTube & X", 64, 36]
    };
    const formats = ["9:16", "1:1", "16:9"].map((r: any) => {
      const m = fmtMeta[r], stt = st.formats[r], prog = st.fmtProg[r];
      return {
        ratio: r, tag: m[0], where: m[1],
        rendering: stt === "rendering", isReady: stt === "ready", isIdle: stt === "idle",
        progLabel: "Rendering " + prog + "%  ·  about " + Math.max(1, Math.round((100 - prog) / 22)) + " min left",
        progStyle: "width:" + prog + "%;height:100%;background:linear-gradient(90deg,#ff8f3d,#ffc36b);border-radius:3px;display:block;transition:width .2s linear",
        cardStyle: "border-radius:16px;border:1px solid " + (stt === "ready" ? "rgba(126,224,168,.28)" : "rgba(150,170,230,.14)") + ";background:rgba(20,25,48,.75)",
        frameStyle: "flex:none;display:flex;align-items:center;justify-content:center;width:64px;height:64px;border-radius:11px;background:rgba(150,170,230,.08);border:1px solid rgba(150,170,230,.14)",
        frameFillStyle: "display:block;width:" + m[2] + "px;height:" + m[3] + "px;border-radius:4px;background:" + (stt === "ready" ? "linear-gradient(150deg,#2f4a9e,#0d1330)" : "rgba(150,170,230,.18)"),
        tagStyle: "padding:3px 8px;border-radius:20px;font:500 10.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;" +
          (stt === "ready" ? "background:rgba(126,224,168,.14);color:#8df0bd;border:1px solid rgba(126,224,168,.28)" : "background:rgba(150,170,230,.1);color:#9aa6cc;border:1px solid rgba(150,170,230,.18)"),
        // phone: button drops full-width under the text so the title never gets starved
        rowStyle: "display:flex;gap:12px;padding:14px;min-width:0;" +
          (phone ? "flex-direction:column;align-items:stretch" : "align-items:center"),
        btnBase: "flex:none;padding:0 14px;border-radius:11px;cursor:pointer;height:44px;display:flex;align-items:center;justify-content:center;text-align:center;font:600 12.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;" +
          (phone ? "width:100%" : "width:158px"),
        action: () => render1(r)
      };
    });
    const anyIdle = Object.values(st.formats).some((v: any) => v === "idle");

    const chip = (c: any) => "display:flex;align-items:center;gap:8px;width:100%;padding:10px 13px;background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.15);border-radius:11px;cursor:pointer;font:450 12.5px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;color:#c3cbe9;min-height:44px";

    return {
      isPhone: phone, isDesktop: !phone,
      phoneWrapStyle: phone ? "width:100%;height:100%" : "display:none",
      deskWrapStyle: phone ? "display:none" : "width:100%;height:100%",
      isOnboard: scr === "onboard", isStart: scr === "start", isRecipe: scr === "recipe",
      isBoard: scr === "board", isDeliver: scr === "deliver", isIdentity: scr === "identity",
      isCredits: scr === "credits", isProfile: scr === "profile", isProjects: scr === "projects",
      goProjects: () => go("projects"),
      projects: [
        { title: "Why Webb sees the past", meta: meta(4, 2, "d"), state: t("Draft", "draft"), good: false, g: "linear-gradient(150deg,#243a7a,#0d1330 70%),radial-gradient(circle at 70% 30%,rgba(255,190,110,.5),transparent 55%)" },
        { title: "Three myths about black holes", meta: meta(3, 5, "d"), state: t("Posted", "posted"), good: true, g: "linear-gradient(150deg,#5a2f6e,#160c28 70%),radial-gradient(circle at 30% 70%,rgba(120,200,255,.45),transparent 55%)" },
        { title: "What a light-year measures", meta: meta(2, 1, "w"), state: t("Posted", "posted"), good: true, g: "linear-gradient(150deg,#1d4a52,#06171a 70%),radial-gradient(circle at 55% 40%,rgba(255,210,120,.4),transparent 55%)" },
        { title: "How big is a black hole?", meta: meta(1, 3, "w"), state: t("Posted", "posted"), good: true, g: "linear-gradient(150deg,#6b4a0d,#150e02 70%),radial-gradient(circle at 40% 60%,rgba(255,206,90,.5),transparent 55%)" }
      ].map((p: any) => ({
        title: p.title, meta: p.meta, state: p.state, open: () => go("board"),
        thumb: "position:relative;display:block;height:96px;background:" + p.g,
        pillStyle: "position:absolute;left:8px;bottom:8px;padding:3px 8px;border-radius:6px;font:600 10px/1.3 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;" +
          (p.good ? "background:rgba(126,224,168,.2);color:#8df0bd;border:1px solid rgba(126,224,168,.35)"
                  : "background:rgba(5,6,15,.75);color:#c3cbe9;border:1px solid rgba(150,170,230,.25)")
      })),
      startIsCanvas: st.startVariant === "canvas", startIsBar: st.startVariant === "bar",
      costIsMeter: st.costVariant === "meter", costIsPill: st.costVariant === "pill",
      showMeter: st.costVariant === "meter" && scr !== "onboard",
      showBalancePill: st.costVariant === "pill" && scr !== "onboard",
      showTabs: scr !== "onboard",
      isProjectsTab: scr === "projects",
      showBack: ["recipe", "board", "deliver", "identity"].indexOf(scr) >= 0,
      showLogo: ["start", "onboard", "profile", "credits", "projects"].indexOf(scr) >= 0,
      goBack: () => go(scr === "recipe" ? "start" : scr === "board" ? "projects" : scr === "deliver" ? "board" : "profile"),
      balance: st.balance,
      screenTitle: my
        ? { onboard: MY.tSetup, start: MY.tNew, recipe: MY.tPlan, board: MY.tBoard, deliver: MY.tDeliver, identity: MY.tIdentity, credits: MY.tCredits, profile: MY.tAccount, projects: MY.tProjects }[scr]
        : (TITLES[scr] || "Projects"),
      isMy: my,
      L: {
        startTitle: t("What are you posting today?", "startTitle"),
        startSub: t("A link, a video, or just an idea. Anything works.", "startSub"),
        canvasPh: t("Paste a link, or describe the short you want…", "canvasPh"),
        attach: t("Attach file", "attach"), record: t("Record", "record"), cont: t("Continue", "cont"),
        tryLabel: t("Try:", "tryLabel"), pickUp: t("Pick up where you left off", "pickUp"), orNew: t("Or start something new", "orNew"),
        fromArticle: t("From your article", "fromArticle"), planLine: t("A one-minute video explaining it, in your voice.", "planLine"),
        adjust: t("Adjust", "adjust"), orElse: t("Or make something else", "orElse"),
        ctaDraft: t("Show me a draft", "ctaDraft"), reassure: t("Watch it first. You only pay more for the parts you want in real video.", "reassure"),
        playAll: t("Play all", "playAll"), boardBanner: t("This is a rough draft. Pick the scenes worth making real.", "boardBanner"),
        addScene: t("＋ Add a scene", "addScene"), deliverBtn: t("Deliver", "deliverBtn"),
        tryAgain: t("Try again", "tryAgain"), changeWords: t("Change words", "changeWords"),
        moveUp: t("Move up", "moveUp"), moveDown: t("Move down", "moveDown"), remove: t("Remove", "remove"),
        deliverSub: t("Make it for the places you post.", "deliverSub"),
        closeNotice: t("You can close this — we'll let you know when it's done.", "closeNotice"),
        postTo: t("Post it to", "postTo"), yourCaption: t("Your caption", "yourCaption"), edit: t("Edit", "edit"),
        idTitle: t("Identity kit", "idTitle"), idSub: t("Set this once. Every video you make will match.", "idSub"),
        yourVoice: t("Your voice", "yourVoice"), usedIn: t("Used in every video you make", "usedIn"),
        ready: t("Ready", "ready"), reRecord: t("Re-record", "reRecord"), hearSample: t("Hear a sample", "hearSample"), del: t("Delete", "del"),
        look: t("Look", "look"), logo: t("Logo", "logo"), palette: t("Palette", "palette"), type: t("Type", "type"),
        introOutro: t("Intro / outro", "introOutro"), captionStyle: t("Caption style", "captionStyle"),
        seriesMem: t("Series memory", "seriesMem"), seriesSub: t("Keep the next video looking like this one", "seriesSub"),
        balance: t("Balance", "balance"), freeLine: t("Free every month. 200 more arrive in 11 days.", "freeLine"),
        costHeading: t("What things cost, in credits", "costHeading"),
        recent: t("Recent activity", "recent"), topUp: t("Top up", "topUp"), noSub: t("No subscription. Credits never expire.", "noSub"),
        thisMonth: t("This month", "thisMonth"), nShorts: t("9 shorts", "nShorts"), across: t("Across 2 series", "across"),
        published: t("@samrivera · 47 shorts published", "published"), voiceReady: t("Voice ready · palette, captions and intro set", "voiceReady"),
        account: t("Account", "account"), signOut: t("Sign out", "signOut"),
        lastStep: t("Last step · one minute", "lastStep"), readAloud: t("Read this out loud", "readAloud"),
        obSub: t("Then every video can be narrated in your own voice — without you recording again.", "obSub"),
        skip: t("Skip for now", "skip"), privacyNote: t("Only you can use this voice. Delete it any time.", "privacyNote"),
        credits: t("credits", "credits"),
        workspace: t("Workspace", "workspace"), freeResets: t("Free tier resets in 11 days", "freeResets"),
        logoPlace: t("Bottom-right, 2s fade", "logoPlace"), stingVal: t("2s logo sting · subscribe card", "stingVal"),
        freePlan: t("Free plan", "freePlan"), bestValue: t("Best value", "bestValue"),
        projects: t("Your projects", "projectsTitle"), newShort: t("New", "newShort"), sideNew: t("New short", "sideNew"),
        videoLang: t("Video language", "videoLang"),
        videoLangHelp: t("The language your videos are spoken and captioned in.", "videoLangHelp")
      },
      s: {
        h1: "font:600 clamp(" + (my ? 21 : 24) + "px," + (my ? 3 : 3.4) + "vw," + (my ? 28 : 34) + "px)/" + (my ? 1.65 : 1.18) + " " + famHead + ";letter-spacing:" + (my ? "0" : "-.02em") + ";margin:0;text-wrap:pretty",
        h2: "font:600 clamp(" + (my ? 19 : 22) + "px,2.9vw," + (my ? 24 : 29) + "px)/" + (my ? 1.6 : 1.25) + " " + famHead + ";letter-spacing:" + (my ? "0" : "-.02em") + ";margin:0;text-wrap:pretty",
        sub: body(my ? 13.5 : 14.5, "#98a2c4"),
        subSm: body(my ? 12.5 : 13.5, "#98a2c4"),
        label: "font:500 12px/" + lhTight + " " + fam + ";color:#9aa6cc",
        bodySm: body(my ? 11.5 : 12, "#6f7aa0"),
        plan: "font:500 clamp(" + (my ? 17 : 20) + "px,2.6vw," + (my ? 21 : 26) + "px)/" + (my ? 1.85 : 1.5) + " " + famHead + ";letter-spacing:" + (my ? "0" : "-.012em") + ";margin:0;text-wrap:pretty;position:relative",
        sceneLine: body(my ? 13 : 14, "#e6ebff", 450),
        noticeStyle: "flex:1;font:400 12.5px/" + (my ? 1.95 : 1.55) + " " + fam + ";color:#a9dcff;text-wrap:pretty",
        btnBig: btnFont, fam, famHead, lh
      },
      navItems, variantGroups, tabs, sideNav,

      shellStyle: phone
        ? "width:392px;height:812px;flex:none;border-radius:46px;padding:5px;background:linear-gradient(160deg,#2b3050,#0b0e1d);box-shadow:0 40px 90px rgba(0,0,0,.6),0 0 0 1px rgba(150,180,255,.14)"
        : "width:min(1300px,100%);height:820px;flex:none;box-shadow:0 40px 90px rgba(0,0,0,.55)",
      phoneHeaderStyle: "display:flex;align-items:center;gap:10px;padding:10px 16px 12px;flex:none;position:relative",
      padStyle: phone ? "padding:16px 18px 34px" : "padding:40px 48px 56px",
      boardPadStyle: phone ? "flex:1;padding:14px 16px 20px" : "flex:1;padding:32px 44px 24px",
      barStyle: (phone ? "position:sticky;bottom:0;padding:12px 16px;" : "position:sticky;bottom:0;padding:16px 44px;") +
        "background:linear-gradient(180deg,rgba(7,10,22,.6),rgba(7,10,22,.97));backdrop-filter:blur(14px);border-top:1px solid rgba(150,170,230,.14);z-index:2",

      phoneScreenStyle: "width:100%;height:100%;display:flex;flex-direction:column;border-radius:40px;overflow:hidden;position:relative;" +
        (nebula
          ? "background:radial-gradient(120% 60% at 78% -6%, rgba(255,168,72,.20), transparent 58%),radial-gradient(110% 55% at 8% 12%, rgba(78,124,255,.24), transparent 60%),radial-gradient(130% 70% at 50% 108%, rgba(150,72,255,.22), transparent 62%),linear-gradient(180deg,#080c1e 0%,#04050e 100%)"
          : "background:linear-gradient(180deg,#0a0d18 0%,#05060d 100%)"),
      deskScreenStyle: "flex:1;min-width:0;overflow-y:auto;position:relative;" +
        (nebula
          ? "background:radial-gradient(70% 50% at 88% -8%, rgba(255,168,72,.16), transparent 60%),radial-gradient(60% 45% at 4% 6%, rgba(78,124,255,.20), transparent 62%),radial-gradient(80% 60% at 50% 112%, rgba(150,72,255,.18), transparent 62%),#060916"
          : "background:#07090f"),
      starsStyle: nebula
        ? "position:absolute;inset:0;pointer-events:none;opacity:.5;background-image:radial-gradient(1.4px 1.4px at 12% 18%, #fff, transparent),radial-gradient(1.2px 1.2px at 68% 9%, #cfe0ff, transparent),radial-gradient(1.6px 1.6px at 84% 44%, #fff, transparent),radial-gradient(1.1px 1.1px at 26% 62%, #ffd9a8, transparent),radial-gradient(1.3px 1.3px at 51% 33%, #fff, transparent),radial-gradient(1px 1px at 8% 82%, #cfe0ff, transparent),radial-gradient(1.5px 1.5px at 92% 74%, #fff, transparent),radial-gradient(1.1px 1.1px at 38% 91%, #fff, transparent),radial-gradient(1.2px 1.2px at 74% 88%, #ffd9a8, transparent),radial-gradient(1px 1px at 58% 70%, #fff, transparent)"
        : "display:none",

      barInnerStyle: "max-width:680px;margin:0 auto;display:flex;gap:12px;" +
        (phone ? "flex-direction:column;align-items:stretch" : "align-items:center"),
      barBtnsStyle: "display:grid;grid-template-columns:96px 1fr;gap:8px;align-items:center;" + (phone ? "" : "flex:none;grid-template-columns:auto auto"),
      meterFillStyle: "width:" + Math.max(6, (st.balance / 200) * 100) + "%;height:100%;border-radius:4px;background:linear-gradient(90deg,#ff8f3d,#ffc36b);transition:width .4s ease;display:block",
      spentFillStyle: "width:" + spentPct + "%;height:100%;background:linear-gradient(90deg,#4a5480,#6d7bb0)",
      pendingFillStyle: "width:" + pendPct + "%;height:100%;background:linear-gradient(90deg,#ff8f3d,#ffc36b);transition:width .3s ease",

      // onboarding
      obSteps: [0, 1, 2].map((i: any) => ({ style: "flex:1;height:4px;border-radius:3px;display:block;background:" + (i <= 2 ? "linear-gradient(90deg,#ff8f3d,#ffc36b)" : "rgba(150,170,230,.2)") })),
      obLine: t("\u201CI make short videos about space, and I want them to sound like me — not like a robot reading a script.\u201D", "obLine"),
      obLineStyle: "margin:0;font:450 clamp(" + (my ? 14 : 16) + "px,2.2vw," + (my ? 17 : 19) + "px)/" + (my ? 2.1 : 1.75) + " " + fam + ";color:#e6ebff;text-align:center;text-wrap:pretty;position:relative",
      waveBars,
      recTime: "0:" + (st.recSecs < 10 ? "0" : "") + st.recSecs + " / 1:00",
      recHint: recDone ? t("That's enough — your voice is ready.", "recDone") : st.recording ? t("Listening… keep reading naturally.", "recGoing") : st.recSecs > 0 ? t("Paused. Tap to keep going.", "recPaused") : t("Tap to start recording.", "recStart"),
      recBtnStyle: "position:relative;width:76px;height:76px;border-radius:50%;border:none;cursor:pointer;display:flex;align-items:center;justify-content:center;padding:0;" +
        (st.recording ? "background:rgba(255,110,110,.16);box-shadow:0 0 0 2px rgba(255,110,110,.5)" : "background:rgba(255,195,107,.14);box-shadow:0 0 0 2px rgba(255,195,107,.45)"),
      recRingStyle: st.recording
        ? "position:absolute;inset:0;border-radius:50%;border:2px solid rgba(255,110,110,.6);animation:lum-ring 1.6s ease-out infinite;display:block"
        : "display:none",
      recIconStyle: st.recording
        ? "width:24px;height:24px;border-radius:6px;background:#ff7a7a;display:block"
        : "width:30px;height:30px;border-radius:50%;background:linear-gradient(135deg,#ffc36b,#ff8f3d);display:block",
      recProgressStyle: "width:" + recPct + "%;height:100%;background:linear-gradient(90deg,#ff8f3d,#ffc36b);border-radius:4px;transition:width .15s linear",
      obDoneLabel: recDone ? t("Finish setup", "finish") : t("Use a stock voice instead", "stockVoice"),
      obDoneStyle: "width:100%;height:52px;display:flex;align-items:center;justify-content:center;padding:0 16px;border-radius:14px;cursor:pointer;font:600 14px/1.65 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;" +
        (recDone ? "background:linear-gradient(135deg,#ffc36b,#ff8f3d);border:none;color:#1a1103;box-shadow:0 8px 26px rgba(255,150,60,.28)"
          : "background:rgba(150,180,255,.10);border:1px solid rgba(150,180,255,.24);color:#c3cbe9"),
      toggleRec: () => toggleRec(),

      // start
      recents: [
        { title: "Webb telescope explainer", meta: meta(4, 2, "d"), thumb: "display:block;height:78px;border-radius:9px;background:linear-gradient(150deg,#243a7a,#0d1330 70%),radial-gradient(circle at 70% 30%,rgba(255,190,110,.5),transparent 55%)" },
        { title: "Three myths about black holes", meta: meta(3, 5, "d"), thumb: "display:block;height:78px;border-radius:9px;background:linear-gradient(150deg,#5a2f6e,#160c28 70%),radial-gradient(circle at 30% 70%,rgba(120,200,255,.45),transparent 55%)" },
        { title: "What a light-year actually measures", meta: meta(2, 1, "w"), thumb: "display:block;height:78px;border-radius:9px;background:linear-gradient(150deg,#1d4a52,#06171a 70%),radial-gradient(circle at 55% 40%,rgba(255,210,120,.4),transparent 55%)" }
      ],
      tryChips: [t("an article link", "chip1"), t("my 40-min podcast", "chip2"), t("a script I wrote", "chip3")],

      // recipe
      recipeChips: [t("For TikTok & Reels", "rc1"), t("Your voice", "rc2"), t("Big bold captions", "rc3")],
      recipes: [
        { name: t("Just me talking", "r1n"), desc: t("Your face and voice", "r1d"), cost: cr(6), c: "#6ec8ff" },
        { name: t("Cut up a long video", "r2n"), desc: t("Find the best bits", "r2d"), cost: cr(3), c: "#b48cff" },
        { name: t("Add subtitles only", "r3n"), desc: t("Keep your video as it is", "r3d"), cost: cr(1), c: "#7ee0a8" }
      ].map((r: any) => ({
        ...r,
        dot: "width:9px;height:9px;border-radius:50%;flex:none;display:block;background:" + r.c + ";box-shadow:0 0 10px " + r.c,
        style: "display:flex;align-items:center;gap:13px;width:100%;padding:13px 15px;background:rgba(20,25,48,.7);border:1px solid rgba(150,170,230,.13);border-radius:14px;cursor:pointer;min-height:56px",
        pick: () => go("board")
      })),
      startPreviewRun: () => go("board"),

      // storyboard
      sceneSummary: my
        ? MY.scenes + " " + st.scenes.length + " · " + MY.real + " " + readyN + " · " + MY.draft + " " + (st.scenes.length - readyN)
        : st.scenes.length + " scenes · " + readyN + " real · " + (st.scenes.length - readyN) + " draft",
      scenes: st.scenes.map((s: any, idx: any) => ({
        n: idx + 1, line: s.line, caption: s.caption, time: s.time, busy: s.busy,
        busyLabel: s.status === "ready" ? t("Redoing this scene only", "busyRedo") : t("Making this scene real", "busyReal"),
        cardStyle: "border-radius:16px;padding:1px;transition:.2s;" +
          (s.sel ? "background:linear-gradient(135deg,rgba(255,195,107,.85),rgba(255,143,61,.5))" : "background:rgba(150,170,230,.15)"),
        innerStyle: "display:flex;gap:12px;padding:12px;border-radius:15px;background:linear-gradient(165deg,rgba(20,25,48,.96),rgba(12,16,34,.96));" +
          (cinema ? "flex-direction:column" : "flex-direction:row"),
        mediaStyle: "position:relative;flex:none;border-radius:11px;overflow:hidden;background:" + s.media + ";" +
          (cinema ? "height:320px;width:180px;align-self:center" : "width:74px;height:126px"),
        skelStyle: s.loaded ? "display:none" : "position:absolute;inset:0;display:block;background:linear-gradient(90deg,rgba(150,170,230,.06),rgba(150,170,230,.2),rgba(150,170,230,.06));background-size:320px 100%;animation:lum-shim 1.2s linear infinite",
        badgeStyle: "position:absolute;bottom:6px;left:6px;padding:3px 7px;border-radius:6px;font:600 9.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;" +
          (s.status === "ready"
            ? "background:rgba(126,224,168,.18);color:#8df0bd;border:1px solid rgba(126,224,168,.35)"
            : "background:rgba(5,6,15,.72);color:#9aa6cc;border:1px solid rgba(150,170,230,.22)"),
        badge: s.busy ? t("Working", "working") : s.status === "ready" ? t("Real", "real") : t("Draft", "draft"),
        makeRealLabel: t("Make this real", "makeReal"), chosenLabel: t("Chosen ✓", "chosen"), realLabel: t("Real video ✓", "realDone"),
        isReady: s.status === "ready", isMarked: s.status !== "ready" && s.sel, isIdle: s.status !== "ready" && !s.sel,
        captionStyle: "padding:4px 8px;border-radius:7px;font:600 10.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;background:rgba(255,195,107,.12);color:#ffc36b;border:1px solid rgba(255,195,107,.22);max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap",
        lineStyle: "margin:0;font:450 " + (my ? 13 : 14) + "px/" + (my ? 2 : 1.65) + " " + fam + ";color:#e6ebff;text-wrap:pretty",
        menuOpen: st.openMenu === s.id,
        onMenu: () => set((x: any) => ({ openMenu: x.openMenu === s.id ? null : s.id })),
        onRegen: () => { set({ openMenu: null }); regen(s.id); },
        onUpgrade: () => toggleSel(s.id),
        onUp: () => move(s.id, -1),
        onDown: () => move(s.id, 1),
        onDelete: () => del(s.id)
      })),
      addScene: () => addScene(),
      selText: sel.length
        ? (my ? MY.scenes + " " + sel.length + " " + MY.chosenN : sel.length + (sel.length === 1 ? " scene" : " scenes") + " chosen")
        : t("Choose the scenes worth making real", "chooseScenes"),
      afterText: sel.length ? st.balance + " → " + (st.balance - selCost) : st.balance + " " + t("credits left", "creditsLeft"),
      hasSelection: sel.length > 0,
      selCost,
      selCostLabel: cr(selCost),
      balanceLeftLabel: st.balance + " " + t("credits left", "creditsLeft"),
      balancePill: cr(st.balance),
      ctaLabel: sel.length ? t("Make them real", "makeThemReal") : t("Save this draft", "saveDraft"),
      ctaStyle: "display:flex;align-items:center;justify-content:center;gap:9px;min-width:0;height:48px;padding:0 16px;border:none;border-radius:12px;cursor:pointer;font:600 13.5px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;" +
        (sel.length
          ? "background:linear-gradient(135deg,#ffc36b,#ff8f3d);color:#1a1103;box-shadow:0 8px 26px rgba(255,150,60,.3)"
          : "background:rgba(150,180,255,.12);color:#dfe6ff;border:1px solid rgba(150,180,255,.28)"),
      upgradeAll: () => runUpgrade(),

      // deliver
      formats,
      renderAllLabel: anyIdle ? t("Make all three", "makeAll") + " · " + cr(4) : t("All three are ready", "allReady"),
      fmtReadyLabel: t("Download", "download"), fmtWorkingLabel: t("Working…", "workingBtn"),
      fmtIdleLabel: t("Make it", "makeIt") + " · " + cr(2),
      renderAllStyle: "display:flex;align-items:center;justify-content:center;height:52px;padding:0 16px;border-radius:14px;cursor:pointer;font:600 15px/1.4 'IBM Plex Sans','Noto Sans Myanmar',sans-serif;" +
        (anyIdle ? "background:linear-gradient(135deg,#ffc36b,#ff8f3d);border:none;color:#1a1103;box-shadow:0 10px 30px rgba(255,150,60,.28)"
          : "background:rgba(126,224,168,.12);border:1px solid rgba(126,224,168,.3);color:#8df0bd;cursor:default"),
      renderAll: () => renderAll(),
      destinations: [
        { name: "TikTok", state: "@samrivera", c: "#6ec8ff" },
        { name: "Reels", state: "@samrivera", c: "#b48cff" },
        { name: "Shorts", state: "@samrivera", c: "#ff8f8f" },
        { name: t("Download", "download"), state: "mp4", c: "#7ee0a8" }
      ].map((d: any) => ({ ...d, style: chip(), dot: "width:8px;height:8px;border-radius:50%;flex:none;display:block;background:" + d.c })),
      hashtags: ["#space", "#jwst", "#astronomy", "#explainer"],

      // identity
      miniWave: [6, 14, 10, 16, 7].map((h: any) => "width:2.5px;height:" + h + "px;background:#ffc36b;border-radius:2px;display:block"),
      palette: ["#0b1024", "#4da3ff", "#b45cff", "#ffc36b"].map((c: any) => "width:22px;height:22px;border-radius:6px;display:block;background:" + c + ";border:1px solid rgba(255,255,255,.14)"),
      captionStyles: capStyles,
      outLangs: [
        ["en", "English", "'IBM Plex Sans',sans-serif", 1.4],
        ["my", "မြန်မာ", "'Noto Sans Myanmar',sans-serif", 2.0],
        ["ja", "日本語", "'Noto Sans JP',sans-serif", 1.5],
        ["ko", "한국어", "'Noto Sans KR',sans-serif", 1.5],
        ["zh", "中文", "'Noto Sans SC',sans-serif", 1.5],
        ["th", "ไทย", "'Noto Sans Thai',sans-serif", 1.9],
        ["vi", "Tiếng Việt", "'IBM Plex Sans',sans-serif", 1.5],
        ["tl", "Tagalog", "'IBM Plex Sans',sans-serif", 1.4]
      ].map(([id, name, f, l]: any) => ({
        name, on: st.outLang === id, off: st.outLang !== id,
        labelStyle: "flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:500 13px/" + l + " " + f + ";color:" + (st.outLang === id ? "#ffc36b" : "#c3cbe9"),
        pick: () => set({ outLang: id })
      })),
      memoryToggleStyle: "width:46px;height:27px;flex:none;border-radius:20px;border:none;cursor:pointer;padding:3px;display:flex;align-items:center;transition:.2s;" +
        (st.memory ? "background:linear-gradient(135deg,#ffc36b,#ff8f3d);justify-content:flex-end" : "background:rgba(150,170,230,.22);justify-content:flex-start"),
      memoryKnobStyle: "width:21px;height:21px;border-radius:50%;background:#fff;display:block;box-shadow:0 2px 6px rgba(0,0,0,.35)",
      toggleMemory: () => set((s: any) => ({ memory: !s.memory })),

      // credits
      priceRows: [
        { label: t("See a draft of your whole video", "p1"), cost: "4", good: true },
        { label: t("Make one scene real", "p2"), cost: "15", good: false },
        { label: t("Save it for one platform", "p3"), cost: "2", good: false },
        { label: t("Try a scene again", "p4"), cost: t("Free", "free"), good: true }
      ].map((p: any) => ({ ...p, costStyle: "font:600 13px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;flex:none;color:" + (p.good ? "#8df0bd" : "#ffc36b") })),
      ledger: [
        { what: t("Made 2 scenes real", "l1"), when: t("Today", "today"), amt: "−30", good: false },
        { what: t("Draft of Webb explainer", "l2"), when: t("Today", "today"), amt: "−4", good: false },
        { what: t("Saved for TikTok", "l3"), when: t("3 days ago", "d3"), amt: "−2", good: false },
        { what: t("Monthly free credits", "l4"), when: t("17 days ago", "d17"), amt: "+200", good: true }
      ].map((l: any) => ({
        ...l,
        dot: "width:8px;height:8px;border-radius:50%;flex:none;display:block;background:" + (l.good ? "#7ee0a8" : "rgba(255,195,107,.7)"),
        amtStyle: "font:600 13.5px/1.65 'Space Grotesk','Noto Sans Myanmar',sans-serif;flex:none;color:" + (l.good ? "#8df0bd" : "#c3cbe9")
      })),
      packs: [
        { credits: "200", price: "$6", best: false },
        { credits: "500", price: "$12", best: true },
        { credits: "1,200", price: "$25", best: false }
      ].map((p: any) => ({
        ...p, buy: () => set((s: any) => ({ balance: s.balance + parseInt(p.credits.replace(",", ""), 10) })),
        style: "display:flex;flex-direction:column;gap:7px;align-items:flex-start;padding:15px;border-radius:15px;cursor:pointer;text-align:left;" +
          (p.best ? "background:rgba(126,224,168,.07);border:1px solid rgba(126,224,168,.3)" : "background:rgba(20,25,48,.75);border:1px solid rgba(150,170,230,.14)")
      })),

      // profile
      accountRows: [
        { label: t("Plan", "plan"), value: t("Free", "freePlan") },
        { label: t("Connected accounts", "connected"), value: t("3 linked", "linked") },
        { label: t("Language", "language"), value: t("English", "myanmar") },
        { label: t("Notifications", "notif"), value: t("When it's done", "whenDone") },
        { label: t("Privacy and data", "privacy"), value: "" }
      ],

      goStart: () => go("start"), goRecipe: () => go("recipe"), goBoard: () => go("board"),
      goDeliver: () => go("deliver"), goIdentity: () => go("identity"),
      goCredits: () => go("credits"), goProfile: () => go("profile"), goOnboard: () => go("onboard")
    };
  
}

export { LINES, MY, SCREENS, TITLES }
