"""initial schema

Revision ID: 369eb92b2137
Revises: 
Create Date: 2026-08-30 02:42:27.532953
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '369eb92b2137'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Every table defaults its primary key to gen_random_uuid(). It is built in on PG13+,
    # but pgcrypto provides it on older servers and the extension is a no-op when it is not
    # needed — cheaper than discovering the difference in production.
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', 'kind', name='uq_assets_sha256_kind')
    )
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('voice_profile_asset_id', sa.UUID(), nullable=True),
    sa.Column('logo_asset_id', sa.UUID(), nullable=True),
    sa.Column('identity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['logo_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_user_id'), 'channels', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('recipe', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('current_plan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_plan_id'], ['plans.id'], name='fk_projects_current_plan', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_channel_id'), 'projects', ['channel_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_plans_project_version')
    )
    op.create_index(op.f('ix_plans_project_id'), 'plans', ['project_id'], unique=False)
    op.create_table('renders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('aspect', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renders_project_id'), 'renders', ['project_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('script_line', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('preview_asset_id', sa.UUID(), nullable=True),
    sa.Column('final_asset_id', sa.UUID(), nullable=True),
    sa.Column('vo_asset_id', sa.UUID(), nullable=True),
    sa.Column('ref_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms > 0', name='ck_scenes_duration_positive'),
    sa.ForeignKeyConstraint(['final_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preview_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['vo_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'index', name='uq_scenes_plan_index')
    )
    op.create_index(op.f('ix_scenes_plan_id'), 'scenes', ['plan_id'], unique=False)
    op.create_index(op.f('ix_scenes_state'), 'scenes', ['state'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('pool', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=96), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('provider_ref', sa.String(length=200), nullable=True),
    sa.Column('estimated_cents', sa.Integer(), nullable=True),
    sa.Column('actual_cents', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['pool', 'status', 'run_after'], unique=False)
    op.create_index('ix_jobs_lease', 'jobs', ['status', 'claimed_until'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_scene_id'), 'jobs', ['scene_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('reserve_entry_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'grant') OR (reserve_entry_id IS NOT NULL) OR (kind = 'reserve')", name='ck_ledger_discharge_references_reserve'),
    sa.CheckConstraint('amount >= 0', name='ck_ledger_amount_non_negative'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reserve_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_user_created', 'ledger_entries', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_ledger_single_discharge', 'ledger_entries', ['reserve_entry_id'], unique=True, postgresql_where=sa.text("kind IN ('commit', 'refund')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ledger_single_discharge', table_name='ledger_entries', postgresql_where=sa.text("kind IN ('commit', 'refund')"))
    op.drop_index('ix_ledger_user_created', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_jobs_scene_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index('ix_jobs_lease', table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_scenes_state'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_plan_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_renders_project_id'), table_name='renders')
    op.drop_table('renders')
    op.drop_index(op.f('ix_plans_project_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_projects_channel_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_channels_user_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_sha256'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
